package com.waipin.model;

public class Banji {
    @Override
    public String toString() {
        return "Banji{" +
                "id=" + id +
                ", banjimingcheng='" + banjimingcheng + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banji.id
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banji.banjimingcheng
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    private String banjimingcheng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banji.id
     *
     * @return the value of banji.id
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banji.id
     *
     * @param id the value for banji.id
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banji.banjimingcheng
     *
     * @return the value of banji.banjimingcheng
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    public String getBanjimingcheng() {
        return banjimingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banji.banjimingcheng
     *
     * @param banjimingcheng the value for banji.banjimingcheng
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    public void setBanjimingcheng(String banjimingcheng) {
        this.banjimingcheng = banjimingcheng == null ? null : banjimingcheng.trim();
    }
}