package com.waipin.model;

public class Chufadengji {
    @Override
    public String toString() {
        return "Chufadengji{" +
                "id=" + id +
                ", chufadengji='" + chufadengji + '\'' +
                ", chufajine=" + chufajine +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chufadengji.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chufadengji.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String chufadengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chufadengji.chufajine
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private Integer chufajine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chufadengji.id
     *
     * @return the value of chufadengji.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chufadengji.id
     *
     * @param id the value for chufadengji.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chufadengji.chufadengji
     *
     * @return the value of chufadengji.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getChufadengji() {
        return chufadengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chufadengji.chufadengji
     *
     * @param chufadengji the value for chufadengji.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setChufadengji(String chufadengji) {
        this.chufadengji = chufadengji == null ? null : chufadengji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chufadengji.chufajine
     *
     * @return the value of chufadengji.chufajine
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Integer getChufajine() {
        return chufajine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chufadengji.chufajine
     *
     * @param chufajine the value for chufadengji.chufajine
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setChufajine(Integer chufajine) {
        this.chufajine = chufajine;
    }
}