package com.waipin.model;

public class Gangqianpeixunziliao {
    @Override
    public String toString() {
        return "Gangqianpeixunziliao{" +
                "id=" + id +
                ", ziliaomingcheng='" + ziliaomingcheng + '\'' +
                ", ziliaolujing='" + ziliaolujing + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gangqianpeixunziliao.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gangqianpeixunziliao.ziliaomingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String ziliaomingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gangqianpeixunziliao.ziliaolujing
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String ziliaolujing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gangqianpeixunziliao.id
     *
     * @return the value of gangqianpeixunziliao.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gangqianpeixunziliao.id
     *
     * @param id the value for gangqianpeixunziliao.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gangqianpeixunziliao.ziliaomingcheng
     *
     * @return the value of gangqianpeixunziliao.ziliaomingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getZiliaomingcheng() {
        return ziliaomingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gangqianpeixunziliao.ziliaomingcheng
     *
     * @param ziliaomingcheng the value for gangqianpeixunziliao.ziliaomingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setZiliaomingcheng(String ziliaomingcheng) {
        this.ziliaomingcheng = ziliaomingcheng == null ? null : ziliaomingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gangqianpeixunziliao.ziliaolujing
     *
     * @return the value of gangqianpeixunziliao.ziliaolujing
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getZiliaolujing() {
        return ziliaolujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gangqianpeixunziliao.ziliaolujing
     *
     * @param ziliaolujing the value for gangqianpeixunziliao.ziliaolujing
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setZiliaolujing(String ziliaolujing) {
        this.ziliaolujing = ziliaolujing == null ? null : ziliaolujing.trim();
    }
}