package com.waipin.model;

public class Guanliyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String yonghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.mima
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String mima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String dianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String youxiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanliyuan.dizhi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    private String dizhi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.id
     *
     * @return the value of guanliyuan.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.id
     *
     * @param id the value for guanliyuan.id
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.yonghuming
     *
     * @return the value of guanliyuan.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.yonghuming
     *
     * @param yonghuming the value for guanliyuan.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.mima
     *
     * @return the value of guanliyuan.mima
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.mima
     *
     * @param mima the value for guanliyuan.mima
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.xingming
     *
     * @return the value of guanliyuan.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.xingming
     *
     * @param xingming the value for guanliyuan.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.xingbie
     *
     * @return the value of guanliyuan.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.xingbie
     *
     * @param xingbie the value for guanliyuan.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.dianhua
     *
     * @return the value of guanliyuan.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getDianhua() {
        return dianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.dianhua
     *
     * @param dianhua the value for guanliyuan.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setDianhua(String dianhua) {
        this.dianhua = dianhua == null ? null : dianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.youxiang
     *
     * @return the value of guanliyuan.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getYouxiang() {
        return youxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.youxiang
     *
     * @param youxiang the value for guanliyuan.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setYouxiang(String youxiang) {
        this.youxiang = youxiang == null ? null : youxiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanliyuan.dizhi
     *
     * @return the value of guanliyuan.dizhi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getDizhi() {
        return dizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanliyuan.dizhi
     *
     * @param dizhi the value for guanliyuan.dizhi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setDizhi(String dizhi) {
        this.dizhi = dizhi == null ? null : dizhi.trim();
    }

    @Override
    public String toString() {
        return "Guanliyuan{" +
                "id=" + id +
                ", yonghuming='" + yonghuming + '\'' +
                ", mima='" + mima + '\'' +
                ", xingming='" + xingming + '\'' +
                ", xingbie='" + xingbie + '\'' +
                ", dianhua='" + dianhua + '\'' +
                ", youxiang='" + youxiang + '\'' +
                ", dizhi='" + dizhi + '\'' +
                '}';
    }
}