package com.waipin.model;

import java.util.Date;

public class Hetong {
    @Override
    public String toString() {
        return "Hetong{" +
                "id=" + id +
                ", jiaoshibianhao=" + jiaoshibianhao +
                ", jiaoshixingming='" + jiaoshixingming + '\'' +
                ", zhuanzhanghuming='" + zhuanzhanghuming + '\'' +
                ", shenfenzheng='" + shenfenzheng + '\'' +
                ", yinhangkahao='" + yinhangkahao + '\'' +
                ", yinhang='" + yinhang + '\'' +
                ", kaihuhanghuhao='" + kaihuhanghuhao + '\'' +
                ", hetongleixing='" + hetongleixing + '\'' +
                ", pinyongxingshi='" + pinyongxingshi + '\'' +
                ", keshidanjia='" + keshidanjia + '\'' +
                ", kechengbianhao='" + kechengbianhao + '\'' +
                ", kechengmingcheng='" + kechengmingcheng + '\'' +
                ", renkebanji='" + renkebanji + '\'' +
                ", zongxueshi='" + zongxueshi + '\'' +
                ", zhuangzhangjine='" + zhuangzhangjine + '\'' +
                ", xueqi='" + xueqi + '\'' +
                ", chuangjianshijian=" + chuangjianshijian +
                ", hetongname='" + hetongname + '\'' +
                ", hetongurl='" + hetongurl + '\'' +
                '}';

    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.id
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.jiaoshibianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private Integer jiaoshibianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.jiaoshixingming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String jiaoshixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.zhuanzhanghuming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String zhuanzhanghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.shenfenzheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String shenfenzheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.yinhangkahao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String yinhangkahao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.yinhang
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String yinhang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.kaihuhanghuhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String kaihuhanghuhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.hetongleixing
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String hetongleixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.pinyongxingshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String pinyongxingshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.keshidanjia
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String keshidanjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.kechengbianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String kechengbianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.kechengmingcheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String kechengmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.renkebanji
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String renkebanji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.zongxueshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String zongxueshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.zhuangzhangjine
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String zhuangzhangjine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.xueqi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String xueqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.chuangjianshijian
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private Date chuangjianshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.hetongname
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String hetongname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.hetongurl
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    private String hetongurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.id
     *
     * @return the value of hetong.id
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.id
     *
     * @param id the value for hetong.id
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.jiaoshibianhao
     *
     * @return the value of hetong.jiaoshibianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public Integer getJiaoshibianhao() {
        return jiaoshibianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.jiaoshibianhao
     *
     * @param jiaoshibianhao the value for hetong.jiaoshibianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setJiaoshibianhao(Integer jiaoshibianhao) {
        this.jiaoshibianhao = jiaoshibianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.jiaoshixingming
     *
     * @return the value of hetong.jiaoshixingming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getJiaoshixingming() {
        return jiaoshixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.jiaoshixingming
     *
     * @param jiaoshixingming the value for hetong.jiaoshixingming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setJiaoshixingming(String jiaoshixingming) {
        this.jiaoshixingming = jiaoshixingming == null ? null : jiaoshixingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.zhuanzhanghuming
     *
     * @return the value of hetong.zhuanzhanghuming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getZhuanzhanghuming() {
        return zhuanzhanghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.zhuanzhanghuming
     *
     * @param zhuanzhanghuming the value for hetong.zhuanzhanghuming
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setZhuanzhanghuming(String zhuanzhanghuming) {
        this.zhuanzhanghuming = zhuanzhanghuming == null ? null : zhuanzhanghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.shenfenzheng
     *
     * @return the value of hetong.shenfenzheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.shenfenzheng
     *
     * @param shenfenzheng the value for hetong.shenfenzheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.yinhangkahao
     *
     * @return the value of hetong.yinhangkahao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getYinhangkahao() {
        return yinhangkahao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.yinhangkahao
     *
     * @param yinhangkahao the value for hetong.yinhangkahao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setYinhangkahao(String yinhangkahao) {
        this.yinhangkahao = yinhangkahao == null ? null : yinhangkahao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.yinhang
     *
     * @return the value of hetong.yinhang
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getYinhang() {
        return yinhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.yinhang
     *
     * @param yinhang the value for hetong.yinhang
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setYinhang(String yinhang) {
        this.yinhang = yinhang == null ? null : yinhang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.kaihuhanghuhao
     *
     * @return the value of hetong.kaihuhanghuhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getKaihuhanghuhao() {
        return kaihuhanghuhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.kaihuhanghuhao
     *
     * @param kaihuhanghuhao the value for hetong.kaihuhanghuhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setKaihuhanghuhao(String kaihuhanghuhao) {
        this.kaihuhanghuhao = kaihuhanghuhao == null ? null : kaihuhanghuhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.hetongleixing
     *
     * @return the value of hetong.hetongleixing
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getHetongleixing() {
        return hetongleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.hetongleixing
     *
     * @param hetongleixing the value for hetong.hetongleixing
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setHetongleixing(String hetongleixing) {
        this.hetongleixing = hetongleixing == null ? null : hetongleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.pinyongxingshi
     *
     * @return the value of hetong.pinyongxingshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getPinyongxingshi() {
        return pinyongxingshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.pinyongxingshi
     *
     * @param pinyongxingshi the value for hetong.pinyongxingshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setPinyongxingshi(String pinyongxingshi) {
        this.pinyongxingshi = pinyongxingshi == null ? null : pinyongxingshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.keshidanjia
     *
     * @return the value of hetong.keshidanjia
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getKeshidanjia() {
        return keshidanjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.keshidanjia
     *
     * @param keshidanjia the value for hetong.keshidanjia
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setKeshidanjia(String keshidanjia) {
        this.keshidanjia = keshidanjia == null ? null : keshidanjia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.kechengbianhao
     *
     * @return the value of hetong.kechengbianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getKechengbianhao() {
        return kechengbianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.kechengbianhao
     *
     * @param kechengbianhao the value for hetong.kechengbianhao
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setKechengbianhao(String kechengbianhao) {
        this.kechengbianhao = kechengbianhao == null ? null : kechengbianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.kechengmingcheng
     *
     * @return the value of hetong.kechengmingcheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getKechengmingcheng() {
        return kechengmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.kechengmingcheng
     *
     * @param kechengmingcheng the value for hetong.kechengmingcheng
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setKechengmingcheng(String kechengmingcheng) {
        this.kechengmingcheng = kechengmingcheng == null ? null : kechengmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.renkebanji
     *
     * @return the value of hetong.renkebanji
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getRenkebanji() {
        return renkebanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.renkebanji
     *
     * @param renkebanji the value for hetong.renkebanji
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setRenkebanji(String renkebanji) {
        this.renkebanji = renkebanji == null ? null : renkebanji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.zongxueshi
     *
     * @return the value of hetong.zongxueshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getZongxueshi() {
        return zongxueshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.zongxueshi
     *
     * @param zongxueshi the value for hetong.zongxueshi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setZongxueshi(String zongxueshi) {
        this.zongxueshi = zongxueshi == null ? null : zongxueshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.zhuangzhangjine
     *
     * @return the value of hetong.zhuangzhangjine
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getZhuangzhangjine() {
        return zhuangzhangjine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.zhuangzhangjine
     *
     * @param zhuangzhangjine the value for hetong.zhuangzhangjine
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setZhuangzhangjine(String zhuangzhangjine) {
        this.zhuangzhangjine = zhuangzhangjine == null ? null : zhuangzhangjine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.xueqi
     *
     * @return the value of hetong.xueqi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getXueqi() {
        return xueqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.xueqi
     *
     * @param xueqi the value for hetong.xueqi
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setXueqi(String xueqi) {
        this.xueqi = xueqi == null ? null : xueqi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.chuangjianshijian
     *
     * @return the value of hetong.chuangjianshijian
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public Date getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.chuangjianshijian
     *
     * @param chuangjianshijian the value for hetong.chuangjianshijian
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setChuangjianshijian(Date chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.hetongname
     *
     * @return the value of hetong.hetongname
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getHetongname() {
        return hetongname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.hetongname
     *
     * @param hetongname the value for hetong.hetongname
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setHetongname(String hetongname) {
        this.hetongname = hetongname == null ? null : hetongname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.hetongurl
     *
     * @return the value of hetong.hetongurl
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public String getHetongurl() {
        return hetongurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.hetongurl
     *
     * @param hetongurl the value for hetong.hetongurl
     *
     * @mbggenerated Wed May 06 22:24:06 CST 2020
     */
    public void setHetongurl(String hetongurl) {
        this.hetongurl = hetongurl == null ? null : hetongurl.trim();
    }
}