package com.waipin.model;

public class Jiaoxuedudao {
    @Override
    public String toString() {
        return "Jiaoxuedudao{" +
                "id=" + id +
                ", jiaoshibianhao=" + jiaoshibianhao +
                ", xingming='" + xingming + '\'' +
                ", tijiaorenbianhao='" + tijiaorenbianhao + '\'' +
                ", chufadengji='" + chufadengji + '\'' +
                ", fashengshjian='" + fashengshjian + '\'' +
                ", chufayuanyin='" + chufayuanyin + '\'' +
                ", chuangjianshijian='" + chuangjianshijian + '\'' +
                ", shenhezhuangtai='" + shenhezhuangtai + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.jiaoshibianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer jiaoshibianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.tijiaorenbianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String tijiaorenbianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String chufadengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.fashengshjian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String fashengshjian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.chufayuanyin
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String chufayuanyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String chuangjianshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoxuedudao.shenhezhuangtai
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String shenhezhuangtai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.id
     *
     * @return the value of jiaoxuedudao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.id
     *
     * @param id the value for jiaoxuedudao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.jiaoshibianhao
     *
     * @return the value of jiaoxuedudao.jiaoshibianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getJiaoshibianhao() {
        return jiaoshibianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.jiaoshibianhao
     *
     * @param jiaoshibianhao the value for jiaoxuedudao.jiaoshibianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setJiaoshibianhao(Integer jiaoshibianhao) {
        this.jiaoshibianhao = jiaoshibianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.xingming
     *
     * @return the value of jiaoxuedudao.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.xingming
     *
     * @param xingming the value for jiaoxuedudao.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.tijiaorenbianhao
     *
     * @return the value of jiaoxuedudao.tijiaorenbianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getTijiaorenbianhao() {
        return tijiaorenbianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.tijiaorenbianhao
     *
     * @param tijiaorenbianhao the value for jiaoxuedudao.tijiaorenbianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setTijiaorenbianhao(String tijiaorenbianhao) {
        this.tijiaorenbianhao = tijiaorenbianhao == null ? null : tijiaorenbianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.chufadengji
     *
     * @return the value of jiaoxuedudao.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getChufadengji() {
        return chufadengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.chufadengji
     *
     * @param chufadengji the value for jiaoxuedudao.chufadengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setChufadengji(String chufadengji) {
        this.chufadengji = chufadengji == null ? null : chufadengji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.fashengshjian
     *
     * @return the value of jiaoxuedudao.fashengshjian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getFashengshjian() {
        return fashengshjian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.fashengshjian
     *
     * @param fashengshjian the value for jiaoxuedudao.fashengshjian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setFashengshjian(String fashengshjian) {
        this.fashengshjian = fashengshjian == null ? null : fashengshjian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.chufayuanyin
     *
     * @return the value of jiaoxuedudao.chufayuanyin
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getChufayuanyin() {
        return chufayuanyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.chufayuanyin
     *
     * @param chufayuanyin the value for jiaoxuedudao.chufayuanyin
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setChufayuanyin(String chufayuanyin) {
        this.chufayuanyin = chufayuanyin == null ? null : chufayuanyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.chuangjianshijian
     *
     * @return the value of jiaoxuedudao.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.chuangjianshijian
     *
     * @param chuangjianshijian the value for jiaoxuedudao.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setChuangjianshijian(String chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian == null ? null : chuangjianshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoxuedudao.shenhezhuangtai
     *
     * @return the value of jiaoxuedudao.shenhezhuangtai
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getShenhezhuangtai() {
        return shenhezhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoxuedudao.shenhezhuangtai
     *
     * @param shenhezhuangtai the value for jiaoxuedudao.shenhezhuangtai
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setShenhezhuangtai(String shenhezhuangtai) {
        this.shenhezhuangtai = shenhezhuangtai == null ? null : shenhezhuangtai.trim();
    }
}