package com.waipin.model;

public class Jiaoshi {
    @Override
    public String toString() {
        return "Jiaoshi{" +
                "id=" + id +
                ", yonghuming='" + yonghuming + '\'' +
                ", mima='" + mima + '\'' +
                ", xingming='" + xingming + '\'' +
                ", xingbie='" + xingbie + '\'' +
                ", dianhua='" + dianhua + '\'' +
                ", canjiagongzuoshijian='" + canjiagongzuoshijian + '\'' +
                ", canjiagongzuoshijianlujing='" + canjiagongzuoshijianlujing + '\'' +
                ", shenfenzheng='" + shenfenzheng + '\'' +
                ", shenfenzhenglujing='" + shenfenzhenglujing + '\'' +
                ", xueweizheng='" + xueweizheng + '\'' +
                ", xueweizhenglujing='" + xueweizhenglujing + '\'' +
                ", xuelizheng='" + xuelizheng + '\'' +
                ", xuelizhenglujing='" + xuelizhenglujing + '\'' +
                ", zhichengzheng='" + zhichengzheng + '\'' +
                ", zhichengzhenglujing='" + zhichengzhenglujing + '\'' +
                ", pingdingdengji='" + pingdingdengji + '\'' +
                ", zongheshuipingfenshu='" + zongheshuipingfenshu + '\'' +
                ", zongheshuipingfenshulujing='" + zongheshuipingfenshulujing + '\'' +
                ", chuangjianshijian='" + chuangjianshijian + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String yonghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String mima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String dianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.canjiagongzuoshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String canjiagongzuoshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.canjiagongzuoshijianlujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String canjiagongzuoshijianlujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.shenfenzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String shenfenzheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.shenfenzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String shenfenzhenglujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xueweizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xueweizheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xueweizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xueweizhenglujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xuelizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xuelizheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.xuelizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xuelizhenglujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.zhichengzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String zhichengzheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.zhichengzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String zhichengzhenglujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.pingdingdengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String pingdingdengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.zongheshuipingfenshu
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String zongheshuipingfenshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.zongheshuipingfenshulujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String zongheshuipingfenshulujing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiaoshi.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String chuangjianshijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.id
     *
     * @return the value of jiaoshi.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.id
     *
     * @param id the value for jiaoshi.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.yonghuming
     *
     * @return the value of jiaoshi.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.yonghuming
     *
     * @param yonghuming the value for jiaoshi.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.mima
     *
     * @return the value of jiaoshi.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.mima
     *
     * @param mima the value for jiaoshi.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xingming
     *
     * @return the value of jiaoshi.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xingming
     *
     * @param xingming the value for jiaoshi.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xingbie
     *
     * @return the value of jiaoshi.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xingbie
     *
     * @param xingbie the value for jiaoshi.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.dianhua
     *
     * @return the value of jiaoshi.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getDianhua() {
        return dianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.dianhua
     *
     * @param dianhua the value for jiaoshi.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setDianhua(String dianhua) {
        this.dianhua = dianhua == null ? null : dianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.canjiagongzuoshijian
     *
     * @return the value of jiaoshi.canjiagongzuoshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getCanjiagongzuoshijian() {
        return canjiagongzuoshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.canjiagongzuoshijian
     *
     * @param canjiagongzuoshijian the value for jiaoshi.canjiagongzuoshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setCanjiagongzuoshijian(String canjiagongzuoshijian) {
        this.canjiagongzuoshijian = canjiagongzuoshijian == null ? null : canjiagongzuoshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.canjiagongzuoshijianlujing
     *
     * @return the value of jiaoshi.canjiagongzuoshijianlujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getCanjiagongzuoshijianlujing() {
        return canjiagongzuoshijianlujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.canjiagongzuoshijianlujing
     *
     * @param canjiagongzuoshijianlujing the value for jiaoshi.canjiagongzuoshijianlujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setCanjiagongzuoshijianlujing(String canjiagongzuoshijianlujing) {
        this.canjiagongzuoshijianlujing = canjiagongzuoshijianlujing == null ? null : canjiagongzuoshijianlujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.shenfenzheng
     *
     * @return the value of jiaoshi.shenfenzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.shenfenzheng
     *
     * @param shenfenzheng the value for jiaoshi.shenfenzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.shenfenzhenglujing
     *
     * @return the value of jiaoshi.shenfenzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getShenfenzhenglujing() {
        return shenfenzhenglujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.shenfenzhenglujing
     *
     * @param shenfenzhenglujing the value for jiaoshi.shenfenzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setShenfenzhenglujing(String shenfenzhenglujing) {
        this.shenfenzhenglujing = shenfenzhenglujing == null ? null : shenfenzhenglujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xueweizheng
     *
     * @return the value of jiaoshi.xueweizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXueweizheng() {
        return xueweizheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xueweizheng
     *
     * @param xueweizheng the value for jiaoshi.xueweizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXueweizheng(String xueweizheng) {
        this.xueweizheng = xueweizheng == null ? null : xueweizheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xueweizhenglujing
     *
     * @return the value of jiaoshi.xueweizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXueweizhenglujing() {
        return xueweizhenglujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xueweizhenglujing
     *
     * @param xueweizhenglujing the value for jiaoshi.xueweizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXueweizhenglujing(String xueweizhenglujing) {
        this.xueweizhenglujing = xueweizhenglujing == null ? null : xueweizhenglujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xuelizheng
     *
     * @return the value of jiaoshi.xuelizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXuelizheng() {
        return xuelizheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xuelizheng
     *
     * @param xuelizheng the value for jiaoshi.xuelizheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXuelizheng(String xuelizheng) {
        this.xuelizheng = xuelizheng == null ? null : xuelizheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.xuelizhenglujing
     *
     * @return the value of jiaoshi.xuelizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXuelizhenglujing() {
        return xuelizhenglujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.xuelizhenglujing
     *
     * @param xuelizhenglujing the value for jiaoshi.xuelizhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXuelizhenglujing(String xuelizhenglujing) {
        this.xuelizhenglujing = xuelizhenglujing == null ? null : xuelizhenglujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.zhichengzheng
     *
     * @return the value of jiaoshi.zhichengzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getZhichengzheng() {
        return zhichengzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.zhichengzheng
     *
     * @param zhichengzheng the value for jiaoshi.zhichengzheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setZhichengzheng(String zhichengzheng) {
        this.zhichengzheng = zhichengzheng == null ? null : zhichengzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.zhichengzhenglujing
     *
     * @return the value of jiaoshi.zhichengzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getZhichengzhenglujing() {
        return zhichengzhenglujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.zhichengzhenglujing
     *
     * @param zhichengzhenglujing the value for jiaoshi.zhichengzhenglujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setZhichengzhenglujing(String zhichengzhenglujing) {
        this.zhichengzhenglujing = zhichengzhenglujing == null ? null : zhichengzhenglujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.pingdingdengji
     *
     * @return the value of jiaoshi.pingdingdengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getPingdingdengji() {
        return pingdingdengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.pingdingdengji
     *
     * @param pingdingdengji the value for jiaoshi.pingdingdengji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setPingdingdengji(String pingdingdengji) {
        this.pingdingdengji = pingdingdengji == null ? null : pingdingdengji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.zongheshuipingfenshu
     *
     * @return the value of jiaoshi.zongheshuipingfenshu
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getZongheshuipingfenshu() {
        return zongheshuipingfenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.zongheshuipingfenshu
     *
     * @param zongheshuipingfenshu the value for jiaoshi.zongheshuipingfenshu
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setZongheshuipingfenshu(String zongheshuipingfenshu) {
        this.zongheshuipingfenshu = zongheshuipingfenshu == null ? null : zongheshuipingfenshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.zongheshuipingfenshulujing
     *
     * @return the value of jiaoshi.zongheshuipingfenshulujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getZongheshuipingfenshulujing() {
        return zongheshuipingfenshulujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.zongheshuipingfenshulujing
     *
     * @param zongheshuipingfenshulujing the value for jiaoshi.zongheshuipingfenshulujing
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setZongheshuipingfenshulujing(String zongheshuipingfenshulujing) {
        this.zongheshuipingfenshulujing = zongheshuipingfenshulujing == null ? null : zongheshuipingfenshulujing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiaoshi.chuangjianshijian
     *
     * @return the value of jiaoshi.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiaoshi.chuangjianshijian
     *
     * @param chuangjianshijian the value for jiaoshi.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setChuangjianshijian(String chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian == null ? null : chuangjianshijian.trim();
    }
}