package com.waipin.model;

import java.util.ArrayList;
import java.util.List;

public class JiaoshiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public JiaoshiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYonghumingIsNull() {
            addCriterion("yonghuming is null");
            return (Criteria) this;
        }

        public Criteria andYonghumingIsNotNull() {
            addCriterion("yonghuming is not null");
            return (Criteria) this;
        }

        public Criteria andYonghumingEqualTo(String value) {
            addCriterion("yonghuming =", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingNotEqualTo(String value) {
            addCriterion("yonghuming <>", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingGreaterThan(String value) {
            addCriterion("yonghuming >", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingGreaterThanOrEqualTo(String value) {
            addCriterion("yonghuming >=", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingLessThan(String value) {
            addCriterion("yonghuming <", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingLessThanOrEqualTo(String value) {
            addCriterion("yonghuming <=", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingLike(String value) {
            addCriterion("yonghuming like", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingNotLike(String value) {
            addCriterion("yonghuming not like", value, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingIn(List<String> values) {
            addCriterion("yonghuming in", values, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingNotIn(List<String> values) {
            addCriterion("yonghuming not in", values, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingBetween(String value1, String value2) {
            addCriterion("yonghuming between", value1, value2, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andYonghumingNotBetween(String value1, String value2) {
            addCriterion("yonghuming not between", value1, value2, "yonghuming");
            return (Criteria) this;
        }

        public Criteria andMimaIsNull() {
            addCriterion("mima is null");
            return (Criteria) this;
        }

        public Criteria andMimaIsNotNull() {
            addCriterion("mima is not null");
            return (Criteria) this;
        }

        public Criteria andMimaEqualTo(String value) {
            addCriterion("mima =", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaNotEqualTo(String value) {
            addCriterion("mima <>", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaGreaterThan(String value) {
            addCriterion("mima >", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaGreaterThanOrEqualTo(String value) {
            addCriterion("mima >=", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaLessThan(String value) {
            addCriterion("mima <", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaLessThanOrEqualTo(String value) {
            addCriterion("mima <=", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaLike(String value) {
            addCriterion("mima like", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaNotLike(String value) {
            addCriterion("mima not like", value, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaIn(List<String> values) {
            addCriterion("mima in", values, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaNotIn(List<String> values) {
            addCriterion("mima not in", values, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaBetween(String value1, String value2) {
            addCriterion("mima between", value1, value2, "mima");
            return (Criteria) this;
        }

        public Criteria andMimaNotBetween(String value1, String value2) {
            addCriterion("mima not between", value1, value2, "mima");
            return (Criteria) this;
        }

        public Criteria andXingmingIsNull() {
            addCriterion("xingming is null");
            return (Criteria) this;
        }

        public Criteria andXingmingIsNotNull() {
            addCriterion("xingming is not null");
            return (Criteria) this;
        }

        public Criteria andXingmingEqualTo(String value) {
            addCriterion("xingming =", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingNotEqualTo(String value) {
            addCriterion("xingming <>", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingGreaterThan(String value) {
            addCriterion("xingming >", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingGreaterThanOrEqualTo(String value) {
            addCriterion("xingming >=", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingLessThan(String value) {
            addCriterion("xingming <", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingLessThanOrEqualTo(String value) {
            addCriterion("xingming <=", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingLike(String value) {
            addCriterion("xingming like", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingNotLike(String value) {
            addCriterion("xingming not like", value, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingIn(List<String> values) {
            addCriterion("xingming in", values, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingNotIn(List<String> values) {
            addCriterion("xingming not in", values, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingBetween(String value1, String value2) {
            addCriterion("xingming between", value1, value2, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingmingNotBetween(String value1, String value2) {
            addCriterion("xingming not between", value1, value2, "xingming");
            return (Criteria) this;
        }

        public Criteria andXingbieIsNull() {
            addCriterion("xingbie is null");
            return (Criteria) this;
        }

        public Criteria andXingbieIsNotNull() {
            addCriterion("xingbie is not null");
            return (Criteria) this;
        }

        public Criteria andXingbieEqualTo(String value) {
            addCriterion("xingbie =", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieNotEqualTo(String value) {
            addCriterion("xingbie <>", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieGreaterThan(String value) {
            addCriterion("xingbie >", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieGreaterThanOrEqualTo(String value) {
            addCriterion("xingbie >=", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieLessThan(String value) {
            addCriterion("xingbie <", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieLessThanOrEqualTo(String value) {
            addCriterion("xingbie <=", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieLike(String value) {
            addCriterion("xingbie like", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieNotLike(String value) {
            addCriterion("xingbie not like", value, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieIn(List<String> values) {
            addCriterion("xingbie in", values, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieNotIn(List<String> values) {
            addCriterion("xingbie not in", values, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieBetween(String value1, String value2) {
            addCriterion("xingbie between", value1, value2, "xingbie");
            return (Criteria) this;
        }

        public Criteria andXingbieNotBetween(String value1, String value2) {
            addCriterion("xingbie not between", value1, value2, "xingbie");
            return (Criteria) this;
        }

        public Criteria andDianhuaIsNull() {
            addCriterion("dianhua is null");
            return (Criteria) this;
        }

        public Criteria andDianhuaIsNotNull() {
            addCriterion("dianhua is not null");
            return (Criteria) this;
        }

        public Criteria andDianhuaEqualTo(String value) {
            addCriterion("dianhua =", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaNotEqualTo(String value) {
            addCriterion("dianhua <>", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaGreaterThan(String value) {
            addCriterion("dianhua >", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaGreaterThanOrEqualTo(String value) {
            addCriterion("dianhua >=", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaLessThan(String value) {
            addCriterion("dianhua <", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaLessThanOrEqualTo(String value) {
            addCriterion("dianhua <=", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaLike(String value) {
            addCriterion("dianhua like", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaNotLike(String value) {
            addCriterion("dianhua not like", value, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaIn(List<String> values) {
            addCriterion("dianhua in", values, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaNotIn(List<String> values) {
            addCriterion("dianhua not in", values, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaBetween(String value1, String value2) {
            addCriterion("dianhua between", value1, value2, "dianhua");
            return (Criteria) this;
        }

        public Criteria andDianhuaNotBetween(String value1, String value2) {
            addCriterion("dianhua not between", value1, value2, "dianhua");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianIsNull() {
            addCriterion("canjiagongzuoshijian is null");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianIsNotNull() {
            addCriterion("canjiagongzuoshijian is not null");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianEqualTo(String value) {
            addCriterion("canjiagongzuoshijian =", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianNotEqualTo(String value) {
            addCriterion("canjiagongzuoshijian <>", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianGreaterThan(String value) {
            addCriterion("canjiagongzuoshijian >", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianGreaterThanOrEqualTo(String value) {
            addCriterion("canjiagongzuoshijian >=", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianLessThan(String value) {
            addCriterion("canjiagongzuoshijian <", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianLessThanOrEqualTo(String value) {
            addCriterion("canjiagongzuoshijian <=", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianLike(String value) {
            addCriterion("canjiagongzuoshijian like", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianNotLike(String value) {
            addCriterion("canjiagongzuoshijian not like", value, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianIn(List<String> values) {
            addCriterion("canjiagongzuoshijian in", values, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianNotIn(List<String> values) {
            addCriterion("canjiagongzuoshijian not in", values, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianBetween(String value1, String value2) {
            addCriterion("canjiagongzuoshijian between", value1, value2, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianNotBetween(String value1, String value2) {
            addCriterion("canjiagongzuoshijian not between", value1, value2, "canjiagongzuoshijian");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingIsNull() {
            addCriterion("canjiagongzuoshijianlujing is null");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingIsNotNull() {
            addCriterion("canjiagongzuoshijianlujing is not null");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingEqualTo(String value) {
            addCriterion("canjiagongzuoshijianlujing =", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingNotEqualTo(String value) {
            addCriterion("canjiagongzuoshijianlujing <>", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingGreaterThan(String value) {
            addCriterion("canjiagongzuoshijianlujing >", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingGreaterThanOrEqualTo(String value) {
            addCriterion("canjiagongzuoshijianlujing >=", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingLessThan(String value) {
            addCriterion("canjiagongzuoshijianlujing <", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingLessThanOrEqualTo(String value) {
            addCriterion("canjiagongzuoshijianlujing <=", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingLike(String value) {
            addCriterion("canjiagongzuoshijianlujing like", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingNotLike(String value) {
            addCriterion("canjiagongzuoshijianlujing not like", value, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingIn(List<String> values) {
            addCriterion("canjiagongzuoshijianlujing in", values, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingNotIn(List<String> values) {
            addCriterion("canjiagongzuoshijianlujing not in", values, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingBetween(String value1, String value2) {
            addCriterion("canjiagongzuoshijianlujing between", value1, value2, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andCanjiagongzuoshijianlujingNotBetween(String value1, String value2) {
            addCriterion("canjiagongzuoshijianlujing not between", value1, value2, "canjiagongzuoshijianlujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengIsNull() {
            addCriterion("shenfenzheng is null");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengIsNotNull() {
            addCriterion("shenfenzheng is not null");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengEqualTo(String value) {
            addCriterion("shenfenzheng =", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengNotEqualTo(String value) {
            addCriterion("shenfenzheng <>", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengGreaterThan(String value) {
            addCriterion("shenfenzheng >", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengGreaterThanOrEqualTo(String value) {
            addCriterion("shenfenzheng >=", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengLessThan(String value) {
            addCriterion("shenfenzheng <", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengLessThanOrEqualTo(String value) {
            addCriterion("shenfenzheng <=", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengLike(String value) {
            addCriterion("shenfenzheng like", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengNotLike(String value) {
            addCriterion("shenfenzheng not like", value, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengIn(List<String> values) {
            addCriterion("shenfenzheng in", values, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengNotIn(List<String> values) {
            addCriterion("shenfenzheng not in", values, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengBetween(String value1, String value2) {
            addCriterion("shenfenzheng between", value1, value2, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhengNotBetween(String value1, String value2) {
            addCriterion("shenfenzheng not between", value1, value2, "shenfenzheng");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingIsNull() {
            addCriterion("shenfenzhenglujing is null");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingIsNotNull() {
            addCriterion("shenfenzhenglujing is not null");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingEqualTo(String value) {
            addCriterion("shenfenzhenglujing =", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingNotEqualTo(String value) {
            addCriterion("shenfenzhenglujing <>", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingGreaterThan(String value) {
            addCriterion("shenfenzhenglujing >", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingGreaterThanOrEqualTo(String value) {
            addCriterion("shenfenzhenglujing >=", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingLessThan(String value) {
            addCriterion("shenfenzhenglujing <", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingLessThanOrEqualTo(String value) {
            addCriterion("shenfenzhenglujing <=", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingLike(String value) {
            addCriterion("shenfenzhenglujing like", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingNotLike(String value) {
            addCriterion("shenfenzhenglujing not like", value, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingIn(List<String> values) {
            addCriterion("shenfenzhenglujing in", values, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingNotIn(List<String> values) {
            addCriterion("shenfenzhenglujing not in", values, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingBetween(String value1, String value2) {
            addCriterion("shenfenzhenglujing between", value1, value2, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andShenfenzhenglujingNotBetween(String value1, String value2) {
            addCriterion("shenfenzhenglujing not between", value1, value2, "shenfenzhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhengIsNull() {
            addCriterion("xueweizheng is null");
            return (Criteria) this;
        }

        public Criteria andXueweizhengIsNotNull() {
            addCriterion("xueweizheng is not null");
            return (Criteria) this;
        }

        public Criteria andXueweizhengEqualTo(String value) {
            addCriterion("xueweizheng =", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengNotEqualTo(String value) {
            addCriterion("xueweizheng <>", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengGreaterThan(String value) {
            addCriterion("xueweizheng >", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengGreaterThanOrEqualTo(String value) {
            addCriterion("xueweizheng >=", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengLessThan(String value) {
            addCriterion("xueweizheng <", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengLessThanOrEqualTo(String value) {
            addCriterion("xueweizheng <=", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengLike(String value) {
            addCriterion("xueweizheng like", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengNotLike(String value) {
            addCriterion("xueweizheng not like", value, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengIn(List<String> values) {
            addCriterion("xueweizheng in", values, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengNotIn(List<String> values) {
            addCriterion("xueweizheng not in", values, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengBetween(String value1, String value2) {
            addCriterion("xueweizheng between", value1, value2, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhengNotBetween(String value1, String value2) {
            addCriterion("xueweizheng not between", value1, value2, "xueweizheng");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingIsNull() {
            addCriterion("xueweizhenglujing is null");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingIsNotNull() {
            addCriterion("xueweizhenglujing is not null");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingEqualTo(String value) {
            addCriterion("xueweizhenglujing =", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingNotEqualTo(String value) {
            addCriterion("xueweizhenglujing <>", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingGreaterThan(String value) {
            addCriterion("xueweizhenglujing >", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingGreaterThanOrEqualTo(String value) {
            addCriterion("xueweizhenglujing >=", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingLessThan(String value) {
            addCriterion("xueweizhenglujing <", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingLessThanOrEqualTo(String value) {
            addCriterion("xueweizhenglujing <=", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingLike(String value) {
            addCriterion("xueweizhenglujing like", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingNotLike(String value) {
            addCriterion("xueweizhenglujing not like", value, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingIn(List<String> values) {
            addCriterion("xueweizhenglujing in", values, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingNotIn(List<String> values) {
            addCriterion("xueweizhenglujing not in", values, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingBetween(String value1, String value2) {
            addCriterion("xueweizhenglujing between", value1, value2, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXueweizhenglujingNotBetween(String value1, String value2) {
            addCriterion("xueweizhenglujing not between", value1, value2, "xueweizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhengIsNull() {
            addCriterion("xuelizheng is null");
            return (Criteria) this;
        }

        public Criteria andXuelizhengIsNotNull() {
            addCriterion("xuelizheng is not null");
            return (Criteria) this;
        }

        public Criteria andXuelizhengEqualTo(String value) {
            addCriterion("xuelizheng =", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengNotEqualTo(String value) {
            addCriterion("xuelizheng <>", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengGreaterThan(String value) {
            addCriterion("xuelizheng >", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengGreaterThanOrEqualTo(String value) {
            addCriterion("xuelizheng >=", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengLessThan(String value) {
            addCriterion("xuelizheng <", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengLessThanOrEqualTo(String value) {
            addCriterion("xuelizheng <=", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengLike(String value) {
            addCriterion("xuelizheng like", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengNotLike(String value) {
            addCriterion("xuelizheng not like", value, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengIn(List<String> values) {
            addCriterion("xuelizheng in", values, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengNotIn(List<String> values) {
            addCriterion("xuelizheng not in", values, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengBetween(String value1, String value2) {
            addCriterion("xuelizheng between", value1, value2, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhengNotBetween(String value1, String value2) {
            addCriterion("xuelizheng not between", value1, value2, "xuelizheng");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingIsNull() {
            addCriterion("xuelizhenglujing is null");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingIsNotNull() {
            addCriterion("xuelizhenglujing is not null");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingEqualTo(String value) {
            addCriterion("xuelizhenglujing =", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingNotEqualTo(String value) {
            addCriterion("xuelizhenglujing <>", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingGreaterThan(String value) {
            addCriterion("xuelizhenglujing >", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingGreaterThanOrEqualTo(String value) {
            addCriterion("xuelizhenglujing >=", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingLessThan(String value) {
            addCriterion("xuelizhenglujing <", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingLessThanOrEqualTo(String value) {
            addCriterion("xuelizhenglujing <=", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingLike(String value) {
            addCriterion("xuelizhenglujing like", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingNotLike(String value) {
            addCriterion("xuelizhenglujing not like", value, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingIn(List<String> values) {
            addCriterion("xuelizhenglujing in", values, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingNotIn(List<String> values) {
            addCriterion("xuelizhenglujing not in", values, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingBetween(String value1, String value2) {
            addCriterion("xuelizhenglujing between", value1, value2, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andXuelizhenglujingNotBetween(String value1, String value2) {
            addCriterion("xuelizhenglujing not between", value1, value2, "xuelizhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengIsNull() {
            addCriterion("zhichengzheng is null");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengIsNotNull() {
            addCriterion("zhichengzheng is not null");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengEqualTo(String value) {
            addCriterion("zhichengzheng =", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengNotEqualTo(String value) {
            addCriterion("zhichengzheng <>", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengGreaterThan(String value) {
            addCriterion("zhichengzheng >", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengGreaterThanOrEqualTo(String value) {
            addCriterion("zhichengzheng >=", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengLessThan(String value) {
            addCriterion("zhichengzheng <", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengLessThanOrEqualTo(String value) {
            addCriterion("zhichengzheng <=", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengLike(String value) {
            addCriterion("zhichengzheng like", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengNotLike(String value) {
            addCriterion("zhichengzheng not like", value, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengIn(List<String> values) {
            addCriterion("zhichengzheng in", values, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengNotIn(List<String> values) {
            addCriterion("zhichengzheng not in", values, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengBetween(String value1, String value2) {
            addCriterion("zhichengzheng between", value1, value2, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhengNotBetween(String value1, String value2) {
            addCriterion("zhichengzheng not between", value1, value2, "zhichengzheng");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingIsNull() {
            addCriterion("zhichengzhenglujing is null");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingIsNotNull() {
            addCriterion("zhichengzhenglujing is not null");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingEqualTo(String value) {
            addCriterion("zhichengzhenglujing =", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingNotEqualTo(String value) {
            addCriterion("zhichengzhenglujing <>", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingGreaterThan(String value) {
            addCriterion("zhichengzhenglujing >", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingGreaterThanOrEqualTo(String value) {
            addCriterion("zhichengzhenglujing >=", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingLessThan(String value) {
            addCriterion("zhichengzhenglujing <", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingLessThanOrEqualTo(String value) {
            addCriterion("zhichengzhenglujing <=", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingLike(String value) {
            addCriterion("zhichengzhenglujing like", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingNotLike(String value) {
            addCriterion("zhichengzhenglujing not like", value, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingIn(List<String> values) {
            addCriterion("zhichengzhenglujing in", values, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingNotIn(List<String> values) {
            addCriterion("zhichengzhenglujing not in", values, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingBetween(String value1, String value2) {
            addCriterion("zhichengzhenglujing between", value1, value2, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andZhichengzhenglujingNotBetween(String value1, String value2) {
            addCriterion("zhichengzhenglujing not between", value1, value2, "zhichengzhenglujing");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiIsNull() {
            addCriterion("pingdingdengji is null");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiIsNotNull() {
            addCriterion("pingdingdengji is not null");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiEqualTo(String value) {
            addCriterion("pingdingdengji =", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiNotEqualTo(String value) {
            addCriterion("pingdingdengji <>", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiGreaterThan(String value) {
            addCriterion("pingdingdengji >", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiGreaterThanOrEqualTo(String value) {
            addCriterion("pingdingdengji >=", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiLessThan(String value) {
            addCriterion("pingdingdengji <", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiLessThanOrEqualTo(String value) {
            addCriterion("pingdingdengji <=", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiLike(String value) {
            addCriterion("pingdingdengji like", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiNotLike(String value) {
            addCriterion("pingdingdengji not like", value, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiIn(List<String> values) {
            addCriterion("pingdingdengji in", values, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiNotIn(List<String> values) {
            addCriterion("pingdingdengji not in", values, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiBetween(String value1, String value2) {
            addCriterion("pingdingdengji between", value1, value2, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andPingdingdengjiNotBetween(String value1, String value2) {
            addCriterion("pingdingdengji not between", value1, value2, "pingdingdengji");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuIsNull() {
            addCriterion("zongheshuipingfenshu is null");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuIsNotNull() {
            addCriterion("zongheshuipingfenshu is not null");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuEqualTo(String value) {
            addCriterion("zongheshuipingfenshu =", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuNotEqualTo(String value) {
            addCriterion("zongheshuipingfenshu <>", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuGreaterThan(String value) {
            addCriterion("zongheshuipingfenshu >", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuGreaterThanOrEqualTo(String value) {
            addCriterion("zongheshuipingfenshu >=", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuLessThan(String value) {
            addCriterion("zongheshuipingfenshu <", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuLessThanOrEqualTo(String value) {
            addCriterion("zongheshuipingfenshu <=", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuLike(String value) {
            addCriterion("zongheshuipingfenshu like", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuNotLike(String value) {
            addCriterion("zongheshuipingfenshu not like", value, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuIn(List<String> values) {
            addCriterion("zongheshuipingfenshu in", values, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuNotIn(List<String> values) {
            addCriterion("zongheshuipingfenshu not in", values, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuBetween(String value1, String value2) {
            addCriterion("zongheshuipingfenshu between", value1, value2, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshuNotBetween(String value1, String value2) {
            addCriterion("zongheshuipingfenshu not between", value1, value2, "zongheshuipingfenshu");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingIsNull() {
            addCriterion("zongheshuipingfenshulujing is null");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingIsNotNull() {
            addCriterion("zongheshuipingfenshulujing is not null");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingEqualTo(String value) {
            addCriterion("zongheshuipingfenshulujing =", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingNotEqualTo(String value) {
            addCriterion("zongheshuipingfenshulujing <>", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingGreaterThan(String value) {
            addCriterion("zongheshuipingfenshulujing >", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingGreaterThanOrEqualTo(String value) {
            addCriterion("zongheshuipingfenshulujing >=", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingLessThan(String value) {
            addCriterion("zongheshuipingfenshulujing <", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingLessThanOrEqualTo(String value) {
            addCriterion("zongheshuipingfenshulujing <=", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingLike(String value) {
            addCriterion("zongheshuipingfenshulujing like", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingNotLike(String value) {
            addCriterion("zongheshuipingfenshulujing not like", value, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingIn(List<String> values) {
            addCriterion("zongheshuipingfenshulujing in", values, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingNotIn(List<String> values) {
            addCriterion("zongheshuipingfenshulujing not in", values, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingBetween(String value1, String value2) {
            addCriterion("zongheshuipingfenshulujing between", value1, value2, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andZongheshuipingfenshulujingNotBetween(String value1, String value2) {
            addCriterion("zongheshuipingfenshulujing not between", value1, value2, "zongheshuipingfenshulujing");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIsNull() {
            addCriterion("chuangjianshijian is null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIsNotNull() {
            addCriterion("chuangjianshijian is not null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianEqualTo(String value) {
            addCriterion("chuangjianshijian =", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotEqualTo(String value) {
            addCriterion("chuangjianshijian <>", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianGreaterThan(String value) {
            addCriterion("chuangjianshijian >", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianGreaterThanOrEqualTo(String value) {
            addCriterion("chuangjianshijian >=", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLessThan(String value) {
            addCriterion("chuangjianshijian <", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLessThanOrEqualTo(String value) {
            addCriterion("chuangjianshijian <=", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLike(String value) {
            addCriterion("chuangjianshijian like", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotLike(String value) {
            addCriterion("chuangjianshijian not like", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIn(List<String> values) {
            addCriterion("chuangjianshijian in", values, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotIn(List<String> values) {
            addCriterion("chuangjianshijian not in", values, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianBetween(String value1, String value2) {
            addCriterion("chuangjianshijian between", value1, value2, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotBetween(String value1, String value2) {
            addCriterion("chuangjianshijian not between", value1, value2, "chuangjianshijian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiaoshi
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 12 01:52:53 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiaoshi
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}