package com.waipin.model;

import java.util.ArrayList;
import java.util.List;

public class KechengExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public KechengExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKechenghaoIsNull() {
            addCriterion("kechenghao is null");
            return (Criteria) this;
        }

        public Criteria andKechenghaoIsNotNull() {
            addCriterion("kechenghao is not null");
            return (Criteria) this;
        }

        public Criteria andKechenghaoEqualTo(String value) {
            addCriterion("kechenghao =", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoNotEqualTo(String value) {
            addCriterion("kechenghao <>", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoGreaterThan(String value) {
            addCriterion("kechenghao >", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoGreaterThanOrEqualTo(String value) {
            addCriterion("kechenghao >=", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoLessThan(String value) {
            addCriterion("kechenghao <", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoLessThanOrEqualTo(String value) {
            addCriterion("kechenghao <=", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoLike(String value) {
            addCriterion("kechenghao like", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoNotLike(String value) {
            addCriterion("kechenghao not like", value, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoIn(List<String> values) {
            addCriterion("kechenghao in", values, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoNotIn(List<String> values) {
            addCriterion("kechenghao not in", values, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoBetween(String value1, String value2) {
            addCriterion("kechenghao between", value1, value2, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechenghaoNotBetween(String value1, String value2) {
            addCriterion("kechenghao not between", value1, value2, "kechenghao");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengIsNull() {
            addCriterion("kechengmingcheng is null");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengIsNotNull() {
            addCriterion("kechengmingcheng is not null");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengEqualTo(String value) {
            addCriterion("kechengmingcheng =", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengNotEqualTo(String value) {
            addCriterion("kechengmingcheng <>", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengGreaterThan(String value) {
            addCriterion("kechengmingcheng >", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengGreaterThanOrEqualTo(String value) {
            addCriterion("kechengmingcheng >=", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengLessThan(String value) {
            addCriterion("kechengmingcheng <", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengLessThanOrEqualTo(String value) {
            addCriterion("kechengmingcheng <=", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengLike(String value) {
            addCriterion("kechengmingcheng like", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengNotLike(String value) {
            addCriterion("kechengmingcheng not like", value, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengIn(List<String> values) {
            addCriterion("kechengmingcheng in", values, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengNotIn(List<String> values) {
            addCriterion("kechengmingcheng not in", values, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengBetween(String value1, String value2) {
            addCriterion("kechengmingcheng between", value1, value2, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andKechengmingchengNotBetween(String value1, String value2) {
            addCriterion("kechengmingcheng not between", value1, value2, "kechengmingcheng");
            return (Criteria) this;
        }

        public Criteria andXuefenIsNull() {
            addCriterion("xuefen is null");
            return (Criteria) this;
        }

        public Criteria andXuefenIsNotNull() {
            addCriterion("xuefen is not null");
            return (Criteria) this;
        }

        public Criteria andXuefenEqualTo(String value) {
            addCriterion("xuefen =", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenNotEqualTo(String value) {
            addCriterion("xuefen <>", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenGreaterThan(String value) {
            addCriterion("xuefen >", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenGreaterThanOrEqualTo(String value) {
            addCriterion("xuefen >=", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenLessThan(String value) {
            addCriterion("xuefen <", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenLessThanOrEqualTo(String value) {
            addCriterion("xuefen <=", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenLike(String value) {
            addCriterion("xuefen like", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenNotLike(String value) {
            addCriterion("xuefen not like", value, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenIn(List<String> values) {
            addCriterion("xuefen in", values, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenNotIn(List<String> values) {
            addCriterion("xuefen not in", values, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenBetween(String value1, String value2) {
            addCriterion("xuefen between", value1, value2, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXuefenNotBetween(String value1, String value2) {
            addCriterion("xuefen not between", value1, value2, "xuefen");
            return (Criteria) this;
        }

        public Criteria andXueshiIsNull() {
            addCriterion("xueshi is null");
            return (Criteria) this;
        }

        public Criteria andXueshiIsNotNull() {
            addCriterion("xueshi is not null");
            return (Criteria) this;
        }

        public Criteria andXueshiEqualTo(String value) {
            addCriterion("xueshi =", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiNotEqualTo(String value) {
            addCriterion("xueshi <>", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiGreaterThan(String value) {
            addCriterion("xueshi >", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiGreaterThanOrEqualTo(String value) {
            addCriterion("xueshi >=", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiLessThan(String value) {
            addCriterion("xueshi <", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiLessThanOrEqualTo(String value) {
            addCriterion("xueshi <=", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiLike(String value) {
            addCriterion("xueshi like", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiNotLike(String value) {
            addCriterion("xueshi not like", value, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiIn(List<String> values) {
            addCriterion("xueshi in", values, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiNotIn(List<String> values) {
            addCriterion("xueshi not in", values, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiBetween(String value1, String value2) {
            addCriterion("xueshi between", value1, value2, "xueshi");
            return (Criteria) this;
        }

        public Criteria andXueshiNotBetween(String value1, String value2) {
            addCriterion("xueshi not between", value1, value2, "xueshi");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangIsNull() {
            addCriterion("jiaoxuedagang is null");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangIsNotNull() {
            addCriterion("jiaoxuedagang is not null");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangEqualTo(String value) {
            addCriterion("jiaoxuedagang =", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangNotEqualTo(String value) {
            addCriterion("jiaoxuedagang <>", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangGreaterThan(String value) {
            addCriterion("jiaoxuedagang >", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangGreaterThanOrEqualTo(String value) {
            addCriterion("jiaoxuedagang >=", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangLessThan(String value) {
            addCriterion("jiaoxuedagang <", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangLessThanOrEqualTo(String value) {
            addCriterion("jiaoxuedagang <=", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangLike(String value) {
            addCriterion("jiaoxuedagang like", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangNotLike(String value) {
            addCriterion("jiaoxuedagang not like", value, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangIn(List<String> values) {
            addCriterion("jiaoxuedagang in", values, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangNotIn(List<String> values) {
            addCriterion("jiaoxuedagang not in", values, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangBetween(String value1, String value2) {
            addCriterion("jiaoxuedagang between", value1, value2, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedagangNotBetween(String value1, String value2) {
            addCriterion("jiaoxuedagang not between", value1, value2, "jiaoxuedagang");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingIsNull() {
            addCriterion("jiaoxuedaganglujing is null");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingIsNotNull() {
            addCriterion("jiaoxuedaganglujing is not null");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingEqualTo(String value) {
            addCriterion("jiaoxuedaganglujing =", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingNotEqualTo(String value) {
            addCriterion("jiaoxuedaganglujing <>", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingGreaterThan(String value) {
            addCriterion("jiaoxuedaganglujing >", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingGreaterThanOrEqualTo(String value) {
            addCriterion("jiaoxuedaganglujing >=", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingLessThan(String value) {
            addCriterion("jiaoxuedaganglujing <", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingLessThanOrEqualTo(String value) {
            addCriterion("jiaoxuedaganglujing <=", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingLike(String value) {
            addCriterion("jiaoxuedaganglujing like", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingNotLike(String value) {
            addCriterion("jiaoxuedaganglujing not like", value, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingIn(List<String> values) {
            addCriterion("jiaoxuedaganglujing in", values, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingNotIn(List<String> values) {
            addCriterion("jiaoxuedaganglujing not in", values, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingBetween(String value1, String value2) {
            addCriterion("jiaoxuedaganglujing between", value1, value2, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andJiaoxuedaganglujingNotBetween(String value1, String value2) {
            addCriterion("jiaoxuedaganglujing not between", value1, value2, "jiaoxuedaganglujing");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIsNull() {
            addCriterion("chuangjianshijian is null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIsNotNull() {
            addCriterion("chuangjianshijian is not null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianEqualTo(String value) {
            addCriterion("chuangjianshijian =", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotEqualTo(String value) {
            addCriterion("chuangjianshijian <>", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianGreaterThan(String value) {
            addCriterion("chuangjianshijian >", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianGreaterThanOrEqualTo(String value) {
            addCriterion("chuangjianshijian >=", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLessThan(String value) {
            addCriterion("chuangjianshijian <", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLessThanOrEqualTo(String value) {
            addCriterion("chuangjianshijian <=", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianLike(String value) {
            addCriterion("chuangjianshijian like", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotLike(String value) {
            addCriterion("chuangjianshijian not like", value, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianIn(List<String> values) {
            addCriterion("chuangjianshijian in", values, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotIn(List<String> values) {
            addCriterion("chuangjianshijian not in", values, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianBetween(String value1, String value2) {
            addCriterion("chuangjianshijian between", value1, value2, "chuangjianshijian");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijianNotBetween(String value1, String value2) {
            addCriterion("chuangjianshijian not between", value1, value2, "chuangjianshijian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kecheng
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 18 10:00:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}