package com.waipin.model;

public class Pingjiao {
    @Override
    public String toString() {
        return "Pingjiao{" +
                "id=" + id +
                ", huodongmingcheng='" + huodongmingcheng + '\'' +
                ", kaishishijian='" + kaishishijian + '\'' +
                ", jieshushijian='" + jieshushijian + '\'' +
                ", kechengmingcheng='" + kechengmingcheng + '\'' +
                ", jiaoshixingming='" + jiaoshixingming + '\'' +
                ", timubianhao='" + timubianhao + '\'' +
                ", pingjunfen=" + pingjunfen +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.huodongmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String huodongmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.kaishishijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String kaishishijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.jieshushijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String jieshushijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.kechengmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String kechengmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.jiaoshixingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String jiaoshixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.timubianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String timubianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjiao.pingjunfen
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Double pingjunfen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.id
     *
     * @return the value of pingjiao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.id
     *
     * @param id the value for pingjiao.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.huodongmingcheng
     *
     * @return the value of pingjiao.huodongmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getHuodongmingcheng() {
        return huodongmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.huodongmingcheng
     *
     * @param huodongmingcheng the value for pingjiao.huodongmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setHuodongmingcheng(String huodongmingcheng) {
        this.huodongmingcheng = huodongmingcheng == null ? null : huodongmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.kaishishijian
     *
     * @return the value of pingjiao.kaishishijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getKaishishijian() {
        return kaishishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.kaishishijian
     *
     * @param kaishishijian the value for pingjiao.kaishishijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setKaishishijian(String kaishishijian) {
        this.kaishishijian = kaishishijian == null ? null : kaishishijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.jieshushijian
     *
     * @return the value of pingjiao.jieshushijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getJieshushijian() {
        return jieshushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.jieshushijian
     *
     * @param jieshushijian the value for pingjiao.jieshushijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setJieshushijian(String jieshushijian) {
        this.jieshushijian = jieshushijian == null ? null : jieshushijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.kechengmingcheng
     *
     * @return the value of pingjiao.kechengmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getKechengmingcheng() {
        return kechengmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.kechengmingcheng
     *
     * @param kechengmingcheng the value for pingjiao.kechengmingcheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setKechengmingcheng(String kechengmingcheng) {
        this.kechengmingcheng = kechengmingcheng == null ? null : kechengmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.jiaoshixingming
     *
     * @return the value of pingjiao.jiaoshixingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getJiaoshixingming() {
        return jiaoshixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.jiaoshixingming
     *
     * @param jiaoshixingming the value for pingjiao.jiaoshixingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setJiaoshixingming(String jiaoshixingming) {
        this.jiaoshixingming = jiaoshixingming == null ? null : jiaoshixingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.timubianhao
     *
     * @return the value of pingjiao.timubianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getTimubianhao() {
        return timubianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.timubianhao
     *
     * @param timubianhao the value for pingjiao.timubianhao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setTimubianhao(String timubianhao) {
        this.timubianhao = timubianhao == null ? null : timubianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjiao.pingjunfen
     *
     * @return the value of pingjiao.pingjunfen
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Double getPingjunfen() {
        return pingjunfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjiao.pingjunfen
     *
     * @param pingjunfen the value for pingjiao.pingjunfen
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setPingjunfen(Double pingjunfen) {
        this.pingjunfen = pingjunfen;
    }
}