package com.waipin.model;

public class Shangkebanji {
    @Override
    public String toString() {
        return "Shangkebanji{" +
                "id=" + id +
                ", kechengid=" + kechengid +
                ", kechengmingcheng='" + kechengmingcheng + '\'' +
                ", banjiid=" + banjiid +
                ", banjimingcheng='" + banjimingcheng + '\'' +
                ", jiaoshiid=" + jiaoshiid +
                ", jiaoshixingming='" + jiaoshixingming + '\'' +
                ", xueqi='" + xueqi + '\'' +
                ", shangkexingshi='" + shangkexingshi + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.id
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.kechengid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private Integer kechengid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.kechengmingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private String kechengmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.banjiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private Integer banjiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.banjimingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private String banjimingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.jiaoshiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private Integer jiaoshiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.jiaoshixingming
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private String jiaoshixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.xueqi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private String xueqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangkebanji.shangkexingshi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    private String shangkexingshi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.id
     *
     * @return the value of shangkebanji.id
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.id
     *
     * @param id the value for shangkebanji.id
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.kechengid
     *
     * @return the value of shangkebanji.kechengid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public Integer getKechengid() {
        return kechengid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.kechengid
     *
     * @param kechengid the value for shangkebanji.kechengid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setKechengid(Integer kechengid) {
        this.kechengid = kechengid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.kechengmingcheng
     *
     * @return the value of shangkebanji.kechengmingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public String getKechengmingcheng() {
        return kechengmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.kechengmingcheng
     *
     * @param kechengmingcheng the value for shangkebanji.kechengmingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setKechengmingcheng(String kechengmingcheng) {
        this.kechengmingcheng = kechengmingcheng == null ? null : kechengmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.banjiid
     *
     * @return the value of shangkebanji.banjiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public Integer getBanjiid() {
        return banjiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.banjiid
     *
     * @param banjiid the value for shangkebanji.banjiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setBanjiid(Integer banjiid) {
        this.banjiid = banjiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.banjimingcheng
     *
     * @return the value of shangkebanji.banjimingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public String getBanjimingcheng() {
        return banjimingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.banjimingcheng
     *
     * @param banjimingcheng the value for shangkebanji.banjimingcheng
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setBanjimingcheng(String banjimingcheng) {
        this.banjimingcheng = banjimingcheng == null ? null : banjimingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.jiaoshiid
     *
     * @return the value of shangkebanji.jiaoshiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public Integer getJiaoshiid() {
        return jiaoshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.jiaoshiid
     *
     * @param jiaoshiid the value for shangkebanji.jiaoshiid
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setJiaoshiid(Integer jiaoshiid) {
        this.jiaoshiid = jiaoshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.jiaoshixingming
     *
     * @return the value of shangkebanji.jiaoshixingming
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public String getJiaoshixingming() {
        return jiaoshixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.jiaoshixingming
     *
     * @param jiaoshixingming the value for shangkebanji.jiaoshixingming
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setJiaoshixingming(String jiaoshixingming) {
        this.jiaoshixingming = jiaoshixingming == null ? null : jiaoshixingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.xueqi
     *
     * @return the value of shangkebanji.xueqi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public String getXueqi() {
        return xueqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.xueqi
     *
     * @param xueqi the value for shangkebanji.xueqi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setXueqi(String xueqi) {
        this.xueqi = xueqi == null ? null : xueqi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangkebanji.shangkexingshi
     *
     * @return the value of shangkebanji.shangkexingshi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public String getShangkexingshi() {
        return shangkexingshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangkebanji.shangkexingshi
     *
     * @param shangkexingshi the value for shangkebanji.shangkexingshi
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    public void setShangkexingshi(String shangkexingshi) {
        this.shangkexingshi = shangkexingshi == null ? null : shangkexingshi.trim();
    }
}