package com.waipin.model;

import java.util.ArrayList;
import java.util.List;

public class ShijiangdanganExample {
    @Override
    public String toString() {
        return "ShijiangdanganExample{" +
                "orderByClause='" + orderByClause + '\'' +
                ", distinct=" + distinct +
                ", oredCriteria=" + oredCriteria +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public ShijiangdanganExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidIsNull() {
            addCriterion("zhuanjiaid is null");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidIsNotNull() {
            addCriterion("zhuanjiaid is not null");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidEqualTo(Integer value) {
            addCriterion("zhuanjiaid =", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidNotEqualTo(Integer value) {
            addCriterion("zhuanjiaid <>", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidGreaterThan(Integer value) {
            addCriterion("zhuanjiaid >", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zhuanjiaid >=", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidLessThan(Integer value) {
            addCriterion("zhuanjiaid <", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidLessThanOrEqualTo(Integer value) {
            addCriterion("zhuanjiaid <=", value, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidIn(List<Integer> values) {
            addCriterion("zhuanjiaid in", values, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidNotIn(List<Integer> values) {
            addCriterion("zhuanjiaid not in", values, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidBetween(Integer value1, Integer value2) {
            addCriterion("zhuanjiaid between", value1, value2, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaidNotBetween(Integer value1, Integer value2) {
            addCriterion("zhuanjiaid not between", value1, value2, "zhuanjiaid");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingIsNull() {
            addCriterion("zhuanjiaxingming is null");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingIsNotNull() {
            addCriterion("zhuanjiaxingming is not null");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingEqualTo(String value) {
            addCriterion("zhuanjiaxingming =", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingNotEqualTo(String value) {
            addCriterion("zhuanjiaxingming <>", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingGreaterThan(String value) {
            addCriterion("zhuanjiaxingming >", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingGreaterThanOrEqualTo(String value) {
            addCriterion("zhuanjiaxingming >=", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingLessThan(String value) {
            addCriterion("zhuanjiaxingming <", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingLessThanOrEqualTo(String value) {
            addCriterion("zhuanjiaxingming <=", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingLike(String value) {
            addCriterion("zhuanjiaxingming like", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingNotLike(String value) {
            addCriterion("zhuanjiaxingming not like", value, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingIn(List<String> values) {
            addCriterion("zhuanjiaxingming in", values, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingNotIn(List<String> values) {
            addCriterion("zhuanjiaxingming not in", values, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingBetween(String value1, String value2) {
            addCriterion("zhuanjiaxingming between", value1, value2, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andZhuanjiaxingmingNotBetween(String value1, String value2) {
            addCriterion("zhuanjiaxingming not between", value1, value2, "zhuanjiaxingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidIsNull() {
            addCriterion("jiaoshiid is null");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidIsNotNull() {
            addCriterion("jiaoshiid is not null");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidEqualTo(Integer value) {
            addCriterion("jiaoshiid =", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidNotEqualTo(Integer value) {
            addCriterion("jiaoshiid <>", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidGreaterThan(Integer value) {
            addCriterion("jiaoshiid >", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiaoshiid >=", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidLessThan(Integer value) {
            addCriterion("jiaoshiid <", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidLessThanOrEqualTo(Integer value) {
            addCriterion("jiaoshiid <=", value, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidIn(List<Integer> values) {
            addCriterion("jiaoshiid in", values, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidNotIn(List<Integer> values) {
            addCriterion("jiaoshiid not in", values, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidBetween(Integer value1, Integer value2) {
            addCriterion("jiaoshiid between", value1, value2, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshiidNotBetween(Integer value1, Integer value2) {
            addCriterion("jiaoshiid not between", value1, value2, "jiaoshiid");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingIsNull() {
            addCriterion("jiaoshixingming is null");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingIsNotNull() {
            addCriterion("jiaoshixingming is not null");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingEqualTo(String value) {
            addCriterion("jiaoshixingming =", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingNotEqualTo(String value) {
            addCriterion("jiaoshixingming <>", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingGreaterThan(String value) {
            addCriterion("jiaoshixingming >", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingGreaterThanOrEqualTo(String value) {
            addCriterion("jiaoshixingming >=", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingLessThan(String value) {
            addCriterion("jiaoshixingming <", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingLessThanOrEqualTo(String value) {
            addCriterion("jiaoshixingming <=", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingLike(String value) {
            addCriterion("jiaoshixingming like", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingNotLike(String value) {
            addCriterion("jiaoshixingming not like", value, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingIn(List<String> values) {
            addCriterion("jiaoshixingming in", values, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingNotIn(List<String> values) {
            addCriterion("jiaoshixingming not in", values, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingBetween(String value1, String value2) {
            addCriterion("jiaoshixingming between", value1, value2, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andJiaoshixingmingNotBetween(String value1, String value2) {
            addCriterion("jiaoshixingming not between", value1, value2, "jiaoshixingming");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengIsNull() {
            addCriterion("shijiangkecheng is null");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengIsNotNull() {
            addCriterion("shijiangkecheng is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengEqualTo(String value) {
            addCriterion("shijiangkecheng =", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengNotEqualTo(String value) {
            addCriterion("shijiangkecheng <>", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengGreaterThan(String value) {
            addCriterion("shijiangkecheng >", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangkecheng >=", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengLessThan(String value) {
            addCriterion("shijiangkecheng <", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengLessThanOrEqualTo(String value) {
            addCriterion("shijiangkecheng <=", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengLike(String value) {
            addCriterion("shijiangkecheng like", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengNotLike(String value) {
            addCriterion("shijiangkecheng not like", value, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengIn(List<String> values) {
            addCriterion("shijiangkecheng in", values, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengNotIn(List<String> values) {
            addCriterion("shijiangkecheng not in", values, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengBetween(String value1, String value2) {
            addCriterion("shijiangkecheng between", value1, value2, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangkechengNotBetween(String value1, String value2) {
            addCriterion("shijiangkecheng not between", value1, value2, "shijiangkecheng");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongIsNull() {
            addCriterion("shijiangneirong is null");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongIsNotNull() {
            addCriterion("shijiangneirong is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongEqualTo(String value) {
            addCriterion("shijiangneirong =", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongNotEqualTo(String value) {
            addCriterion("shijiangneirong <>", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongGreaterThan(String value) {
            addCriterion("shijiangneirong >", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangneirong >=", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongLessThan(String value) {
            addCriterion("shijiangneirong <", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongLessThanOrEqualTo(String value) {
            addCriterion("shijiangneirong <=", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongLike(String value) {
            addCriterion("shijiangneirong like", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongNotLike(String value) {
            addCriterion("shijiangneirong not like", value, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongIn(List<String> values) {
            addCriterion("shijiangneirong in", values, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongNotIn(List<String> values) {
            addCriterion("shijiangneirong not in", values, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongBetween(String value1, String value2) {
            addCriterion("shijiangneirong between", value1, value2, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongNotBetween(String value1, String value2) {
            addCriterion("shijiangneirong not between", value1, value2, "shijiangneirong");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlIsNull() {
            addCriterion("shijiangneirongurl is null");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlIsNotNull() {
            addCriterion("shijiangneirongurl is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlEqualTo(String value) {
            addCriterion("shijiangneirongurl =", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlNotEqualTo(String value) {
            addCriterion("shijiangneirongurl <>", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlGreaterThan(String value) {
            addCriterion("shijiangneirongurl >", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangneirongurl >=", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlLessThan(String value) {
            addCriterion("shijiangneirongurl <", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlLessThanOrEqualTo(String value) {
            addCriterion("shijiangneirongurl <=", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlLike(String value) {
            addCriterion("shijiangneirongurl like", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlNotLike(String value) {
            addCriterion("shijiangneirongurl not like", value, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlIn(List<String> values) {
            addCriterion("shijiangneirongurl in", values, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlNotIn(List<String> values) {
            addCriterion("shijiangneirongurl not in", values, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlBetween(String value1, String value2) {
            addCriterion("shijiangneirongurl between", value1, value2, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangneirongurlNotBetween(String value1, String value2) {
            addCriterion("shijiangneirongurl not between", value1, value2, "shijiangneirongurl");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangIsNull() {
            addCriterion("shijiangtigang is null");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangIsNotNull() {
            addCriterion("shijiangtigang is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangEqualTo(String value) {
            addCriterion("shijiangtigang =", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangNotEqualTo(String value) {
            addCriterion("shijiangtigang <>", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangGreaterThan(String value) {
            addCriterion("shijiangtigang >", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangtigang >=", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangLessThan(String value) {
            addCriterion("shijiangtigang <", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangLessThanOrEqualTo(String value) {
            addCriterion("shijiangtigang <=", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangLike(String value) {
            addCriterion("shijiangtigang like", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangNotLike(String value) {
            addCriterion("shijiangtigang not like", value, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangIn(List<String> values) {
            addCriterion("shijiangtigang in", values, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangNotIn(List<String> values) {
            addCriterion("shijiangtigang not in", values, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangBetween(String value1, String value2) {
            addCriterion("shijiangtigang between", value1, value2, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangtigangNotBetween(String value1, String value2) {
            addCriterion("shijiangtigang not between", value1, value2, "shijiangtigang");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaIsNull() {
            addCriterion("shijiangpingjia is null");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaIsNotNull() {
            addCriterion("shijiangpingjia is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaEqualTo(String value) {
            addCriterion("shijiangpingjia =", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaNotEqualTo(String value) {
            addCriterion("shijiangpingjia <>", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaGreaterThan(String value) {
            addCriterion("shijiangpingjia >", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangpingjia >=", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaLessThan(String value) {
            addCriterion("shijiangpingjia <", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaLessThanOrEqualTo(String value) {
            addCriterion("shijiangpingjia <=", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaLike(String value) {
            addCriterion("shijiangpingjia like", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaNotLike(String value) {
            addCriterion("shijiangpingjia not like", value, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaIn(List<String> values) {
            addCriterion("shijiangpingjia in", values, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaNotIn(List<String> values) {
            addCriterion("shijiangpingjia not in", values, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaBetween(String value1, String value2) {
            addCriterion("shijiangpingjia between", value1, value2, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangpingjiaNotBetween(String value1, String value2) {
            addCriterion("shijiangpingjia not between", value1, value2, "shijiangpingjia");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuIsNull() {
            addCriterion("shijiangfenshu is null");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuIsNotNull() {
            addCriterion("shijiangfenshu is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuEqualTo(Integer value) {
            addCriterion("shijiangfenshu =", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuNotEqualTo(Integer value) {
            addCriterion("shijiangfenshu <>", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuGreaterThan(Integer value) {
            addCriterion("shijiangfenshu >", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuGreaterThanOrEqualTo(Integer value) {
            addCriterion("shijiangfenshu >=", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuLessThan(Integer value) {
            addCriterion("shijiangfenshu <", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuLessThanOrEqualTo(Integer value) {
            addCriterion("shijiangfenshu <=", value, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuIn(List<Integer> values) {
            addCriterion("shijiangfenshu in", values, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuNotIn(List<Integer> values) {
            addCriterion("shijiangfenshu not in", values, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuBetween(Integer value1, Integer value2) {
            addCriterion("shijiangfenshu between", value1, value2, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuNotBetween(Integer value1, Integer value2) {
            addCriterion("shijiangfenshu not between", value1, value2, "shijiangfenshu");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlIsNull() {
            addCriterion("shijiangfenshuurl is null");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlIsNotNull() {
            addCriterion("shijiangfenshuurl is not null");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlEqualTo(String value) {
            addCriterion("shijiangfenshuurl =", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlNotEqualTo(String value) {
            addCriterion("shijiangfenshuurl <>", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlGreaterThan(String value) {
            addCriterion("shijiangfenshuurl >", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlGreaterThanOrEqualTo(String value) {
            addCriterion("shijiangfenshuurl >=", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlLessThan(String value) {
            addCriterion("shijiangfenshuurl <", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlLessThanOrEqualTo(String value) {
            addCriterion("shijiangfenshuurl <=", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlLike(String value) {
            addCriterion("shijiangfenshuurl like", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlNotLike(String value) {
            addCriterion("shijiangfenshuurl not like", value, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlIn(List<String> values) {
            addCriterion("shijiangfenshuurl in", values, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlNotIn(List<String> values) {
            addCriterion("shijiangfenshuurl not in", values, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlBetween(String value1, String value2) {
            addCriterion("shijiangfenshuurl between", value1, value2, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andShijiangfenshuurlNotBetween(String value1, String value2) {
            addCriterion("shijiangfenshuurl not between", value1, value2, "shijiangfenshuurl");
            return (Criteria) this;
        }

        public Criteria andXingshiIsNull() {
            addCriterion("xingshi is null");
            return (Criteria) this;
        }

        public Criteria andXingshiIsNotNull() {
            addCriterion("xingshi is not null");
            return (Criteria) this;
        }

        public Criteria andXingshiEqualTo(String value) {
            addCriterion("xingshi =", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiNotEqualTo(String value) {
            addCriterion("xingshi <>", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiGreaterThan(String value) {
            addCriterion("xingshi >", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiGreaterThanOrEqualTo(String value) {
            addCriterion("xingshi >=", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiLessThan(String value) {
            addCriterion("xingshi <", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiLessThanOrEqualTo(String value) {
            addCriterion("xingshi <=", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiLike(String value) {
            addCriterion("xingshi like", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiNotLike(String value) {
            addCriterion("xingshi not like", value, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiIn(List<String> values) {
            addCriterion("xingshi in", values, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiNotIn(List<String> values) {
            addCriterion("xingshi not in", values, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiBetween(String value1, String value2) {
            addCriterion("xingshi between", value1, value2, "xingshi");
            return (Criteria) this;
        }

        public Criteria andXingshiNotBetween(String value1, String value2) {
            addCriterion("xingshi not between", value1, value2, "xingshi");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangIsNull() {
            addCriterion("chuangjianshijiang is null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangIsNotNull() {
            addCriterion("chuangjianshijiang is not null");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangEqualTo(String value) {
            addCriterion("chuangjianshijiang =", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangNotEqualTo(String value) {
            addCriterion("chuangjianshijiang <>", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangGreaterThan(String value) {
            addCriterion("chuangjianshijiang >", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangGreaterThanOrEqualTo(String value) {
            addCriterion("chuangjianshijiang >=", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangLessThan(String value) {
            addCriterion("chuangjianshijiang <", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangLessThanOrEqualTo(String value) {
            addCriterion("chuangjianshijiang <=", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangLike(String value) {
            addCriterion("chuangjianshijiang like", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangNotLike(String value) {
            addCriterion("chuangjianshijiang not like", value, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangIn(List<String> values) {
            addCriterion("chuangjianshijiang in", values, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangNotIn(List<String> values) {
            addCriterion("chuangjianshijiang not in", values, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangBetween(String value1, String value2) {
            addCriterion("chuangjianshijiang between", value1, value2, "chuangjianshijiang");
            return (Criteria) this;
        }

        public Criteria andChuangjianshijiangNotBetween(String value1, String value2) {
            addCriterion("chuangjianshijiang not between", value1, value2, "chuangjianshijiang");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shijiangdangan
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 20 22:07:35 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shijiangdangan
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}