package com.waipin.model;

public class Shijiangdangan {
    @Override
    public String toString() {
        return "Shijiangdangan{" +
                "id=" + id +
                ", zhuanjiaid=" + zhuanjiaid +
                ", zhuanjiaxingming='" + zhuanjiaxingming + '\'' +
                ", jiaoshiid=" + jiaoshiid +
                ", jiaoshixingming='" + jiaoshixingming + '\'' +
                ", shijiangkecheng='" + shijiangkecheng + '\'' +
                ", shijiangneirong='" + shijiangneirong + '\'' +
                ", shijiangneirongurl='" + shijiangneirongurl + '\'' +
                ", shijiangtigang='" + shijiangtigang + '\'' +
                ", shijiangpingjia='" + shijiangpingjia + '\'' +
                ", shijiangfenshu=" + shijiangfenshu +
                ", shijiangfenshuurl='" + shijiangfenshuurl + '\'' +
                ", xingshi='" + xingshi + '\'' +
                ", chuangjianshijiang='" + chuangjianshijiang + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.id
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.zhuanjiaid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private Integer zhuanjiaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.zhuanjiaxingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String zhuanjiaxingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.jiaoshiid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private Integer jiaoshiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.jiaoshixingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String jiaoshixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangkecheng
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangkecheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangneirong
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangneirong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangneirongurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangneirongurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangtigang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangtigang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangpingjia
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangpingjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangfenshu
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private Integer shijiangfenshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.shijiangfenshuurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String shijiangfenshuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.xingshi
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String xingshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shijiangdangan.chuangjianshijiang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    private String chuangjianshijiang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.id
     *
     * @return the value of shijiangdangan.id
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.id
     *
     * @param id the value for shijiangdangan.id
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.zhuanjiaid
     *
     * @return the value of shijiangdangan.zhuanjiaid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Integer getZhuanjiaid() {
        return zhuanjiaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.zhuanjiaid
     *
     * @param zhuanjiaid the value for shijiangdangan.zhuanjiaid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setZhuanjiaid(Integer zhuanjiaid) {
        this.zhuanjiaid = zhuanjiaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.zhuanjiaxingming
     *
     * @return the value of shijiangdangan.zhuanjiaxingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getZhuanjiaxingming() {
        return zhuanjiaxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.zhuanjiaxingming
     *
     * @param zhuanjiaxingming the value for shijiangdangan.zhuanjiaxingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setZhuanjiaxingming(String zhuanjiaxingming) {
        this.zhuanjiaxingming = zhuanjiaxingming == null ? null : zhuanjiaxingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.jiaoshiid
     *
     * @return the value of shijiangdangan.jiaoshiid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Integer getJiaoshiid() {
        return jiaoshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.jiaoshiid
     *
     * @param jiaoshiid the value for shijiangdangan.jiaoshiid
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setJiaoshiid(Integer jiaoshiid) {
        this.jiaoshiid = jiaoshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.jiaoshixingming
     *
     * @return the value of shijiangdangan.jiaoshixingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getJiaoshixingming() {
        return jiaoshixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.jiaoshixingming
     *
     * @param jiaoshixingming the value for shijiangdangan.jiaoshixingming
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setJiaoshixingming(String jiaoshixingming) {
        this.jiaoshixingming = jiaoshixingming == null ? null : jiaoshixingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangkecheng
     *
     * @return the value of shijiangdangan.shijiangkecheng
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangkecheng() {
        return shijiangkecheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangkecheng
     *
     * @param shijiangkecheng the value for shijiangdangan.shijiangkecheng
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangkecheng(String shijiangkecheng) {
        this.shijiangkecheng = shijiangkecheng == null ? null : shijiangkecheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangneirong
     *
     * @return the value of shijiangdangan.shijiangneirong
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangneirong() {
        return shijiangneirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangneirong
     *
     * @param shijiangneirong the value for shijiangdangan.shijiangneirong
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangneirong(String shijiangneirong) {
        this.shijiangneirong = shijiangneirong == null ? null : shijiangneirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangneirongurl
     *
     * @return the value of shijiangdangan.shijiangneirongurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangneirongurl() {
        return shijiangneirongurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangneirongurl
     *
     * @param shijiangneirongurl the value for shijiangdangan.shijiangneirongurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangneirongurl(String shijiangneirongurl) {
        this.shijiangneirongurl = shijiangneirongurl == null ? null : shijiangneirongurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangtigang
     *
     * @return the value of shijiangdangan.shijiangtigang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangtigang() {
        return shijiangtigang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangtigang
     *
     * @param shijiangtigang the value for shijiangdangan.shijiangtigang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangtigang(String shijiangtigang) {
        this.shijiangtigang = shijiangtigang == null ? null : shijiangtigang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangpingjia
     *
     * @return the value of shijiangdangan.shijiangpingjia
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangpingjia() {
        return shijiangpingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangpingjia
     *
     * @param shijiangpingjia the value for shijiangdangan.shijiangpingjia
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangpingjia(String shijiangpingjia) {
        this.shijiangpingjia = shijiangpingjia == null ? null : shijiangpingjia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangfenshu
     *
     * @return the value of shijiangdangan.shijiangfenshu
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public Integer getShijiangfenshu() {
        return shijiangfenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangfenshu
     *
     * @param shijiangfenshu the value for shijiangdangan.shijiangfenshu
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangfenshu(Integer shijiangfenshu) {
        this.shijiangfenshu = shijiangfenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.shijiangfenshuurl
     *
     * @return the value of shijiangdangan.shijiangfenshuurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getShijiangfenshuurl() {
        return shijiangfenshuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.shijiangfenshuurl
     *
     * @param shijiangfenshuurl the value for shijiangdangan.shijiangfenshuurl
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setShijiangfenshuurl(String shijiangfenshuurl) {
        this.shijiangfenshuurl = shijiangfenshuurl == null ? null : shijiangfenshuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.xingshi
     *
     * @return the value of shijiangdangan.xingshi
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getXingshi() {
        return xingshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.xingshi
     *
     * @param xingshi the value for shijiangdangan.xingshi
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setXingshi(String xingshi) {
        this.xingshi = xingshi == null ? null : xingshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shijiangdangan.chuangjianshijiang
     *
     * @return the value of shijiangdangan.chuangjianshijiang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public String getChuangjianshijiang() {
        return chuangjianshijiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shijiangdangan.chuangjianshijiang
     *
     * @param chuangjianshijiang the value for shijiangdangan.chuangjianshijiang
     *
     * @mbggenerated Mon Apr 20 22:07:35 CST 2020
     */
    public void setChuangjianshijiang(String chuangjianshijiang) {
        this.chuangjianshijiang = chuangjianshijiang == null ? null : chuangjianshijiang.trim();
    }
}