package com.waipin.model;

public class User {
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", yonghuming='" + yonghuming + '\'' +
                ", mima='" + mima + '\'' +
                ", shenfen='" + shenfen + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yonghuming
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    private String yonghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mima
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    private String mima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shenfen
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    private String shenfen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yonghuming
     *
     * @return the value of user.yonghuming
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yonghuming
     *
     * @param yonghuming the value for user.yonghuming
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mima
     *
     * @return the value of user.mima
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mima
     *
     * @param mima the value for user.mima
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shenfen
     *
     * @return the value of user.shenfen
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public String getShenfen() {
        return shenfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shenfen
     *
     * @param shenfen the value for user.shenfen
     *
     * @mbggenerated Wed Apr 15 23:23:02 CST 2020
     */
    public void setShenfen(String shenfen) {
        this.shenfen = shenfen == null ? null : shenfen.trim();
    }
}