package com.waipin.model;

public class Xinshui {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinshui.id
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinshui.dengji
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    private String dengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinshui.waipin
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    private Integer waipin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinshui.paiqian
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    private Integer paiqian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinshui.id
     *
     * @return the value of xinshui.id
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinshui.id
     *
     * @param id the value for xinshui.id
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinshui.dengji
     *
     * @return the value of xinshui.dengji
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public String getDengji() {
        return dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinshui.dengji
     *
     * @param dengji the value for xinshui.dengji
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setDengji(String dengji) {
        this.dengji = dengji == null ? null : dengji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinshui.waipin
     *
     * @return the value of xinshui.waipin
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public Integer getWaipin() {
        return waipin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinshui.waipin
     *
     * @param waipin the value for xinshui.waipin
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setWaipin(Integer waipin) {
        this.waipin = waipin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinshui.paiqian
     *
     * @return the value of xinshui.paiqian
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public Integer getPaiqian() {
        return paiqian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinshui.paiqian
     *
     * @param paiqian the value for xinshui.paiqian
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setPaiqian(Integer paiqian) {
        this.paiqian = paiqian;
    }
}