package com.waipin.model;

import java.util.ArrayList;
import java.util.List;

public class XinshuiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public XinshuiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDengjiIsNull() {
            addCriterion("dengji is null");
            return (Criteria) this;
        }

        public Criteria andDengjiIsNotNull() {
            addCriterion("dengji is not null");
            return (Criteria) this;
        }

        public Criteria andDengjiEqualTo(String value) {
            addCriterion("dengji =", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiNotEqualTo(String value) {
            addCriterion("dengji <>", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiGreaterThan(String value) {
            addCriterion("dengji >", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiGreaterThanOrEqualTo(String value) {
            addCriterion("dengji >=", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiLessThan(String value) {
            addCriterion("dengji <", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiLessThanOrEqualTo(String value) {
            addCriterion("dengji <=", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiLike(String value) {
            addCriterion("dengji like", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiNotLike(String value) {
            addCriterion("dengji not like", value, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiIn(List<String> values) {
            addCriterion("dengji in", values, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiNotIn(List<String> values) {
            addCriterion("dengji not in", values, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiBetween(String value1, String value2) {
            addCriterion("dengji between", value1, value2, "dengji");
            return (Criteria) this;
        }

        public Criteria andDengjiNotBetween(String value1, String value2) {
            addCriterion("dengji not between", value1, value2, "dengji");
            return (Criteria) this;
        }

        public Criteria andWaipinIsNull() {
            addCriterion("waipin is null");
            return (Criteria) this;
        }

        public Criteria andWaipinIsNotNull() {
            addCriterion("waipin is not null");
            return (Criteria) this;
        }

        public Criteria andWaipinEqualTo(Integer value) {
            addCriterion("waipin =", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinNotEqualTo(Integer value) {
            addCriterion("waipin <>", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinGreaterThan(Integer value) {
            addCriterion("waipin >", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinGreaterThanOrEqualTo(Integer value) {
            addCriterion("waipin >=", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinLessThan(Integer value) {
            addCriterion("waipin <", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinLessThanOrEqualTo(Integer value) {
            addCriterion("waipin <=", value, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinIn(List<Integer> values) {
            addCriterion("waipin in", values, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinNotIn(List<Integer> values) {
            addCriterion("waipin not in", values, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinBetween(Integer value1, Integer value2) {
            addCriterion("waipin between", value1, value2, "waipin");
            return (Criteria) this;
        }

        public Criteria andWaipinNotBetween(Integer value1, Integer value2) {
            addCriterion("waipin not between", value1, value2, "waipin");
            return (Criteria) this;
        }

        public Criteria andPaiqianIsNull() {
            addCriterion("paiqian is null");
            return (Criteria) this;
        }

        public Criteria andPaiqianIsNotNull() {
            addCriterion("paiqian is not null");
            return (Criteria) this;
        }

        public Criteria andPaiqianEqualTo(Integer value) {
            addCriterion("paiqian =", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianNotEqualTo(Integer value) {
            addCriterion("paiqian <>", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianGreaterThan(Integer value) {
            addCriterion("paiqian >", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianGreaterThanOrEqualTo(Integer value) {
            addCriterion("paiqian >=", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianLessThan(Integer value) {
            addCriterion("paiqian <", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianLessThanOrEqualTo(Integer value) {
            addCriterion("paiqian <=", value, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianIn(List<Integer> values) {
            addCriterion("paiqian in", values, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianNotIn(List<Integer> values) {
            addCriterion("paiqian not in", values, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianBetween(Integer value1, Integer value2) {
            addCriterion("paiqian between", value1, value2, "paiqian");
            return (Criteria) this;
        }

        public Criteria andPaiqianNotBetween(Integer value1, Integer value2) {
            addCriterion("paiqian not between", value1, value2, "paiqian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinshui
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 24 23:45:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinshui
     *
     * @mbggenerated Fri Apr 24 23:45:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}