package com.waipin.model;

public class Xuesheng {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.xuehao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer xuehao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.banji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String banji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String yonghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String mima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuesheng.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String chuangjianshijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.xuehao
     *
     * @return the value of xuesheng.xuehao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getXuehao() {
        return xuehao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.xuehao
     *
     * @param xuehao the value for xuesheng.xuehao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXuehao(Integer xuehao) {
        this.xuehao = xuehao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.xingming
     *
     * @return the value of xuesheng.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.xingming
     *
     * @param xingming the value for xuesheng.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.xingbie
     *
     * @return the value of xuesheng.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.xingbie
     *
     * @param xingbie the value for xuesheng.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.banji
     *
     * @return the value of xuesheng.banji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getBanji() {
        return banji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.banji
     *
     * @param banji the value for xuesheng.banji
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setBanji(String banji) {
        this.banji = banji == null ? null : banji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.yonghuming
     *
     * @return the value of xuesheng.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.yonghuming
     *
     * @param yonghuming the value for xuesheng.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.mima
     *
     * @return the value of xuesheng.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.mima
     *
     * @param mima the value for xuesheng.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuesheng.chuangjianshijian
     *
     * @return the value of xuesheng.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuesheng.chuangjianshijian
     *
     * @param chuangjianshijian the value for xuesheng.chuangjianshijian
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setChuangjianshijian(String chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian == null ? null : chuangjianshijian.trim();
    }
}