package com.waipin.model;

public class Xuewei {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuewei.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuewei.xuewei
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private String xuewei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuewei.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer fenshu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuewei.id
     *
     * @return the value of xuewei.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuewei.id
     *
     * @param id the value for xuewei.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuewei.xuewei
     *
     * @return the value of xuewei.xuewei
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public String getXuewei() {
        return xuewei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuewei.xuewei
     *
     * @param xuewei the value for xuewei.xuewei
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setXuewei(String xuewei) {
        this.xuewei = xuewei == null ? null : xuewei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuewei.fenshu
     *
     * @return the value of xuewei.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getFenshu() {
        return fenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuewei.fenshu
     *
     * @param fenshu the value for xuewei.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setFenshu(Integer fenshu) {
        this.fenshu = fenshu;
    }
}