package com.waipin.model;

public class Zhicheng {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhicheng.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhicheng.zhicheng
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private String zhicheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhicheng.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer fenshu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhicheng.id
     *
     * @return the value of zhicheng.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhicheng.id
     *
     * @param id the value for zhicheng.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhicheng.zhicheng
     *
     * @return the value of zhicheng.zhicheng
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public String getZhicheng() {
        return zhicheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhicheng.zhicheng
     *
     * @param zhicheng the value for zhicheng.zhicheng
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setZhicheng(String zhicheng) {
        this.zhicheng = zhicheng == null ? null : zhicheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhicheng.fenshu
     *
     * @return the value of zhicheng.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getFenshu() {
        return fenshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhicheng.fenshu
     *
     * @param fenshu the value for zhicheng.fenshu
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setFenshu(Integer fenshu) {
        this.fenshu = fenshu;
    }
}