package com.waipin.model;

public class Zhuanjia {
    @Override
    public String toString() {
        return "Zhuanjia{" +
                "id=" + id +
                ", yonghuming='" + yonghuming + '\'' +
                ", mima='" + mima + '\'' +
                ", xingming='" + xingming + '\'' +
                ", xingbie='" + xingbie + '\'' +
                ", dianhua='" + dianhua + '\'' +
                ", youxiang='" + youxiang + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String yonghuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String mima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String dianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhuanjia.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    private String youxiang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.id
     *
     * @return the value of zhuanjia.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.id
     *
     * @param id the value for zhuanjia.id
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.yonghuming
     *
     * @return the value of zhuanjia.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.yonghuming
     *
     * @param yonghuming the value for zhuanjia.yonghuming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.mima
     *
     * @return the value of zhuanjia.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.mima
     *
     * @param mima the value for zhuanjia.mima
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.xingming
     *
     * @return the value of zhuanjia.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.xingming
     *
     * @param xingming the value for zhuanjia.xingming
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.xingbie
     *
     * @return the value of zhuanjia.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.xingbie
     *
     * @param xingbie the value for zhuanjia.xingbie
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.dianhua
     *
     * @return the value of zhuanjia.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getDianhua() {
        return dianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.dianhua
     *
     * @param dianhua the value for zhuanjia.dianhua
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setDianhua(String dianhua) {
        this.dianhua = dianhua == null ? null : dianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhuanjia.youxiang
     *
     * @return the value of zhuanjia.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public String getYouxiang() {
        return youxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhuanjia.youxiang
     *
     * @param youxiang the value for zhuanjia.youxiang
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    public void setYouxiang(String youxiang) {
        this.youxiang = youxiang == null ? null : youxiang.trim();
    }
}