package com.waipin.model;

public class Zonghepingdingjieguo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zonghepingdingjieguo.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zonghepingdingjieguo.zuidifen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer zuidifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zonghepingdingjieguo.zuigaofen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private Integer zuigaofen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zonghepingdingjieguo.dengji
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    private String dengji;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zonghepingdingjieguo.id
     *
     * @return the value of zonghepingdingjieguo.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zonghepingdingjieguo.id
     *
     * @param id the value for zonghepingdingjieguo.id
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zonghepingdingjieguo.zuidifen
     *
     * @return the value of zonghepingdingjieguo.zuidifen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getZuidifen() {
        return zuidifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zonghepingdingjieguo.zuidifen
     *
     * @param zuidifen the value for zonghepingdingjieguo.zuidifen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setZuidifen(Integer zuidifen) {
        this.zuidifen = zuidifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zonghepingdingjieguo.zuigaofen
     *
     * @return the value of zonghepingdingjieguo.zuigaofen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public Integer getZuigaofen() {
        return zuigaofen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zonghepingdingjieguo.zuigaofen
     *
     * @param zuigaofen the value for zonghepingdingjieguo.zuigaofen
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setZuigaofen(Integer zuigaofen) {
        this.zuigaofen = zuigaofen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zonghepingdingjieguo.dengji
     *
     * @return the value of zonghepingdingjieguo.dengji
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public String getDengji() {
        return dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zonghepingdingjieguo.dengji
     *
     * @param dengji the value for zonghepingdingjieguo.dengji
     *
     * @mbggenerated Mon Apr 20 16:26:17 CST 2020
     */
    public void setDengji(String dengji) {
        this.dengji = dengji == null ? null : dengji.trim();
    }
}