package com.waipin.mapper;

import com.waipin.model.Banji;
import com.waipin.model.BanjiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BanjiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int countByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int deleteByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int insert(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int insertSelective(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    List<Banji> selectByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    Banji selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Banji record, @Param("example") BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int updateByExample(@Param("record") Banji record, @Param("example") BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int updateByPrimaryKeySelective(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated Wed Apr 15 23:17:11 CST 2020
     */
    int updateByPrimaryKey(Banji record);
}