package com.waipin.mapper;

import com.waipin.model.Gangqianpeixunziliao;
import com.waipin.model.GangqianpeixunziliaoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GangqianpeixunziliaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int countByExample(GangqianpeixunziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int deleteByExample(GangqianpeixunziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int insert(Gangqianpeixunziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int insertSelective(Gangqianpeixunziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    List<Gangqianpeixunziliao> selectByExample(GangqianpeixunziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    Gangqianpeixunziliao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Gangqianpeixunziliao record, @Param("example") GangqianpeixunziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByExample(@Param("record") Gangqianpeixunziliao record, @Param("example") GangqianpeixunziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByPrimaryKeySelective(Gangqianpeixunziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gangqianpeixunziliao
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByPrimaryKey(Gangqianpeixunziliao record);
}