package com.waipin.mapper;

import com.waipin.model.Gongzi;
import com.waipin.model.GongziExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GongziMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int countByExample(GongziExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int deleteByExample(GongziExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int insert(Gongzi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int insertSelective(Gongzi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    List<Gongzi> selectByExample(GongziExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    Gongzi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") Gongzi record, @Param("example") GongziExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int updateByExample(@Param("record") Gongzi record, @Param("example") GongziExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int updateByPrimaryKeySelective(Gongzi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzi
     *
     * @mbggenerated Sun Apr 26 12:39:50 CST 2020
     */
    int updateByPrimaryKey(Gongzi record);
}