package com.waipin.mapper;

import com.waipin.model.*;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GuanliyuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     *
     */
    Guanliyuan login(Map<String,Object> map);
    Guanliyuan fingbyyonghuming(String yonghuming);
    List<Guanliyuan> findall();
    public int save( String yonghuming, String mima);
    void updateuserinfo(Map<String,Object> map);
    User selectuserid(Map<String,Object> map);
    User selectuseryonghuming(Map<String,Object> map);
    /*********教师管理************************/
    List<Jiaoshi> selectAllteacher(Map<String,Object> map);
    List<Jiaoshi> selectTeacherBypage(Map<String,Object> map);
    boolean updateTeachercanjiagongzuoshijianlujing(Map<String,Object> map);
    boolean updateTeachershenfenzhenglujing(Map<String,Object> map);
    boolean updateTeacherxueweizhenglujing(Map<String,Object> map);
    boolean updateTeacherxuelizhenglujing(Map<String,Object> map);
    boolean updateTeacherzhichengzhenglujing(Map<String,Object> map);
    boolean updateTeacherzongheshuipingfenshulujing(Map<String,Object> map);
    /*********教学督导管理************************/
    List<Jiaoxuedudao> selectAlljiaoxuedudao(Map<String,Object> map);
    List<Jiaoxuedudao> selectJxuedudaoBypage(Map<String,Object> map);

    /*********处罚等级管理************************/
    List<Chufadengji> selectAllchufadengji();
    List<Xuewei> selectAllxuewei();
    List<Zhicheng> selectAllzhicheng();
    List<Gongzuonianxian> selectAllgongzuonianxian();
    List<Zonghepingdingjieguo> selectAllzonghepingdingjieguo();
    List<Xinshui> selectAllxinshui();
    /*********学生管理************************/
    List<Xuesheng> selectAllxuesheng(Map<String,Object> map);
    List<Xuesheng> selectxueshengBypage(Map<String,Object> map);
    /*********课程管理************************/
    List<Kecheng> selectAllkecheng(Map<String,Object> map);
    List<Kecheng> selectkechengBypage(Map<String,Object> map);
    boolean updateKechengjiaoxuedaganglujing(Map<String,Object> map);
    String selectxueshiBykechengming(Map<String,Object> map);
    /*********岗前培训资料管理************************/
    List<Gangqianpeixunziliao> selectAllgangqianpeixunziliao(Map<String,Object> map);
    List<Gangqianpeixunziliao> selectgangqianpeixunziliaoBypage(Map<String,Object> map);
    boolean updateGangqianpeixunziliaolujing(Map<String,Object> map);
    /*********班级管理************************/
    List<Banji> selectAllbanji(Map<String,Object> map);
    List<Banji> selectbanjiBypage(Map<String,Object> map);
    /*********上课班级管理************************/
    List<Shangkebanji> selectAllshangkebanji(Map<String,Object> map);

    List<Shangkebanji> selectshangkebanjiBypage(Map<String,Object> map);
    List<Shangkebanji> selectshangkebanjiByjiaoshiid(Map<String,Object> map);
    /*********专家管理************************/
    List<Zhuanjia> selectAllzhuanjia();
    List<Zhuanjia> selectzhuanjiaBypage(Map<String,Object> map);
    /*********试讲管理************************/
    List<Shijiangdangan> selectAllshijiang(Map<String,Object> map);
    List<Shijiangdangan> selectshijiangBypage(Map<String,Object> map);
    boolean updateShijiangneirongurl(Map<String,Object> map);
    boolean updateShijiangfenshuurl(Map<String,Object> map);
    Xuewei fenshuselectByxuewei(Map<String,Object> map);
    Zhicheng fenshuselectByzhicheng(Map<String,Object> map);
    List<Shijiangdangan> fenshuselectByshijiang(Map<String,Object> map);
    /******************合同管理************************************/
    List<Hetong> selectAllhetong(Map<String,Object> map);
    List<Hetong> selectHetongBypage(Map<String,Object> map);
    List<Hetong> selectHetongdanganBypage(Map<String,Object> map);
    /************************last*********************************/
    int selectjiaoxuedudaoLastid();
    int selectjiaoshiLastid();
    int selectkechengLastid();
    int selectbanjiLastid();
    int selecthetongLastid();
    int selectchufadengjiLastid();
    int selectgangqianpeixunziliaoLastid();
    int selectgongziLastid();
    int selectgongzuonianxianLastid();
    int selectshangkebanjiLastid();
    int selectshijiangdanganLastid();
    int selectxinshuiLastid();
    int selectxueshengLastid();
    int selectxueweiLastid();
    int selectzhichengLastid();
    int selectzhuanjiaLastid();
    int selectzonghepingdingjieguoLastid();
    /***********************工资***********************************/
    List<Gongzi> selectgongziBytime(Map<String,Object> map);
    List<Gongzi> selectByjiaoshibianhaoandcjsj(Map<String,Object> map);
    List<Gongzi> selectAllgongzidangan(Map<String,Object> map);
    List<Gongzi> yijianshengchenggongzi(Map<String,Object> map);
    boolean updategongzifakuaninfo(Map<String,Object> map);
    List<Gongzi> selectByjiaoshibianhaoandshijian(Map<String,Object> map);
    List<Gongzi> selectGongzidanganBypage(Map<String,Object> map);









    int countByExample(GuanliyuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int deleteByExample(GuanliyuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int insert(Guanliyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int insertSelective(Guanliyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    List<Guanliyuan> selectByExample(GuanliyuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    Guanliyuan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Guanliyuan record, @Param("example") GuanliyuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByExample(@Param("record") Guanliyuan record, @Param("example") GuanliyuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByPrimaryKeySelective(Guanliyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanliyuan
     *
     * @mbggenerated Sun Apr 12 01:52:52 CST 2020
     */
    int updateByPrimaryKey(Guanliyuan record);
}