package com.waipin.mapper;

import com.waipin.model.Kecheng;
import com.waipin.model.KechengExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KechengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int countByExample(KechengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int deleteByExample(KechengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int insert(Kecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int insertSelective(Kecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    List<Kecheng> selectByExample(KechengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    Kecheng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Kecheng record, @Param("example") KechengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int updateByExample(@Param("record") Kecheng record, @Param("example") KechengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int updateByPrimaryKeySelective(Kecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbggenerated Sat Apr 18 10:00:24 CST 2020
     */
    int updateByPrimaryKey(Kecheng record);
}