package com.waipin.mapper;

import com.waipin.model.Pingjiao;
import com.waipin.model.PingjiaoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PingjiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int countByExample(PingjiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int deleteByExample(PingjiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int insert(Pingjiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int insertSelective(Pingjiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    List<Pingjiao> selectByExample(PingjiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    Pingjiao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Pingjiao record, @Param("example") PingjiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByExample(@Param("record") Pingjiao record, @Param("example") PingjiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByPrimaryKeySelective(Pingjiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjiao
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByPrimaryKey(Pingjiao record);
}