package com.waipin.mapper;

import com.waipin.model.Shangkebanji;
import com.waipin.model.ShangkebanjiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShangkebanjiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int countByExample(ShangkebanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int deleteByExample(ShangkebanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int insert(Shangkebanji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int insertSelective(Shangkebanji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    List<Shangkebanji> selectByExample(ShangkebanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    Shangkebanji selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Shangkebanji record, @Param("example") ShangkebanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int updateByExample(@Param("record") Shangkebanji record, @Param("example") ShangkebanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int updateByPrimaryKeySelective(Shangkebanji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangkebanji
     *
     * @mbggenerated Thu May 07 17:44:55 CST 2020
     */
    int updateByPrimaryKey(Shangkebanji record);
}