package com.waipin.mapper;

import com.waipin.model.Xuesheng;
import com.waipin.model.XueshengExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XueshengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */


    Xuesheng login(String yonghuming, String  mima);
    int countByExample(XueshengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int deleteByExample(XueshengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int deleteByPrimaryKey(Integer xuehao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int insert(Xuesheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int insertSelective(Xuesheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    List<Xuesheng> selectByExample(XueshengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    Xuesheng selectByPrimaryKey(Integer xuehao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Xuesheng record, @Param("example") XueshengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByExample(@Param("record") Xuesheng record, @Param("example") XueshengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByPrimaryKeySelective(Xuesheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuesheng
     *
     * @mbggenerated Sun Apr 12 01:52:53 CST 2020
     */
    int updateByPrimaryKey(Xuesheng record);
}